package kernel

import (
	"strings"
	"testing"
)

// Forgetext: what this kernel owes, stated without reference to any other
// implementation.
//
// Split out of forgetext_differential_test.go, which compares this kernel against the
// Python one and goes when it does. These say what the behaviour *is*, and
// stay. Keeping both in one file meant a whole-file deletion would have taken
// the second half with the first -- measured, that cost twenty points of
// coverage nobody intended to give up.

func TestTheSanitizerCorpusExercisesBothOutcomes(t *testing.T) {
	// Self-vacuity. A corpus that only contained acceptable inputs would agree
	// with any implementation that accepted everything, and one that only
	// contained refusals would agree with any that refused everything.
	accepted, refused := 0, 0
	for _, probe := range append(append([]struct {
		function string
		input    string
	}{}, sanitizerProbes...), lengthProbes()...) {
		var err error
		if probe.function == "free" {
			_, err = SanitizeFreeText(probe.input, "field")
		} else {
			_, err = SanitizeTitleText(probe.input, "field")
		}
		if err == nil {
			accepted++
			continue
		}
		refused++
	}
	if accepted < 5 || refused < 5 {
		t.Errorf("the corpus accepts %d and refuses %d; it needs both in quantity",
			accepted, refused)
	}
}

func TestTaskHashIsStableAndShort(t *testing.T) {
	// The task hash marks a forge artifact as belonging to a task, and issue
	// reconciliation matches on it. A change here orphans every issue this
	// kernel has ever created.
	hash := TaskHash("TASK-1")
	if len(hash) != 16 {
		t.Errorf("TaskHash returned %d characters", len(hash))
	}
	if hash != TaskHash("TASK-1") {
		t.Error("TaskHash is not stable")
	}
	if hash == TaskHash("TASK-2") {
		t.Error("two task ids share a hash")
	}
	// Pinned against the Python implementation's value for the same input.
	if expected := hexSHA256([]byte("TASK-1"))[:16]; hash != expected {
		t.Errorf("TaskHash = %s, want %s", hash, expected)
	}
}

// sanitizerProbes are (function, input) pairs. Kept as data so the same list
// drives the Python side.
var sanitizerProbes = []struct {
	function string
	input    string
}{
	// Ordinary text, which must survive untouched.
	{"free", "A perfectly ordinary rationale."},
	{"free", "Multiple\nlines\nof text."},
	{"free", "Unicode is fine: café, naïve, 日本語, emoji 🚀."},
	{"free", ""},

	// References, neutralised rather than refused.
	{"free", "Ask @octocat about it."},
	{"free", "email-like not-a-mention@example.com stays as it is"},
	{"free", "See #123 for context."},
	{"free", "See acme/app#456 for context."},
	{"free", "Both @octocat and #123 in one line."},
	{"free", "@start-of-string mention"},
	{"free", "#1 at the very start"},
	{"free", "not#123 because it follows a word character"},

	// Quick actions, refused.
	{"free", "/close"},
	{"free", "ordinary line\n/assign @someone"},
	{"free", "   /close with leading whitespace"},
	{"free", "a/b is not a quick action"},

	// Reserved provenance prefixes, refused.
	{"free", "> Machine-generated by agentic-sdlc."},
	{"free", "fine\n> ref something"},
	{"free", "> parent 12"},
	{"free", "> not a reserved prefix"},

	// Control and separator characters, refused.
	{"free", "vertical\vtab"},
	{"free", "form\ffeed"},
	{"free", "file\x1cseparator"},
	{"free", "group\x1dseparator"},
	{"free", "record\x1eseparator"},
	{"free", "next\u0085line"},
	{"free", "line\u2028separator"},
	{"free", "paragraph\u2029separator"},
	{"free", "carriage\rreturn is allowed"},
	{"free", "tab\tis allowed"},

	// Titles: printable ASCII only, after NFKC.
	{"title", "An Ordinary Title"},
	{"title", "  padded  "},
	{"title", ""},
	{"title", "   "},
	{"title", "-leading dash"},
	{"title", "/leading slash"},
	{"title", "café"},
	{"title", "日本語"},
	{"title", "ﬁ ligature normalises to ASCII"},
	{"title", "①"},
	{"title", "full－width hyphen normalises"},
	{"title", "tab\tinside"},
	{"title", "trailing dash-"},
}

// Length probes, built rather than written out. The limits are in characters,
// not bytes, and every one of these is non-ASCII precisely so an
// implementation that counted bytes would refuse an input Python accepts.

func lengthProbes() []struct {
	function string
	input    string
} {
	type probe = struct {
		function string
		input    string
	}
	return []probe{
		{"free", strings.Repeat("é", 4000)},
		{"free", strings.Repeat("é", 4001)},
		{"free", strings.Repeat("日", 3999)},
		{"title", strings.Repeat("a", 200)},
		{"title", strings.Repeat("a", 201)},
	}
}
