package kernel

import (
	"encoding/json"
	"fmt"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

// The forge text sanitizers, compared with the Python implementation on the
// same inputs.
//
// These functions are pure, so the comparison can be exhaustive in a way the
// command-level differentials cannot: every input below is run through both
// implementations in one pass and compared on both the verdict and the exact
// message. That matters here because the message is what an operator reads to
// find out which field of which file to fix.
//
// The inputs are chosen to be nasty rather than realistic. Sanitization is
// only interesting at the boundary: the character that renders as nothing, the
// line that a forge reads as a command, the reference that notifies somebody.

// sanitizerProbes are (function, input) pairs. Kept as data so the same list
// drives the Python side.
var sanitizerProbes = []struct {
	function string
	input    string
}{
	// Ordinary text, which must survive untouched.
	{"free", "A perfectly ordinary rationale."},
	{"free", "Multiple\nlines\nof text."},
	{"free", "Unicode is fine: café, naïve, 日本語, emoji 🚀."},
	{"free", ""},

	// References, neutralised rather than refused.
	{"free", "Ask @octocat about it."},
	{"free", "email-like not-a-mention@example.com stays as it is"},
	{"free", "See #123 for context."},
	{"free", "See acme/app#456 for context."},
	{"free", "Both @octocat and #123 in one line."},
	{"free", "@start-of-string mention"},
	{"free", "#1 at the very start"},
	{"free", "not#123 because it follows a word character"},

	// Quick actions, refused.
	{"free", "/close"},
	{"free", "ordinary line\n/assign @someone"},
	{"free", "   /close with leading whitespace"},
	{"free", "a/b is not a quick action"},

	// Reserved provenance prefixes, refused.
	{"free", "> Machine-generated by agentic-sdlc."},
	{"free", "fine\n> ref something"},
	{"free", "> parent 12"},
	{"free", "> not a reserved prefix"},

	// Control and separator characters, refused.
	{"free", "vertical\vtab"},
	{"free", "form\ffeed"},
	{"free", "file\x1cseparator"},
	{"free", "group\x1dseparator"},
	{"free", "record\x1eseparator"},
	{"free", "next\u0085line"},
	{"free", "line\u2028separator"},
	{"free", "paragraph\u2029separator"},
	{"free", "carriage\rreturn is allowed"},
	{"free", "tab\tis allowed"},

	// Titles: printable ASCII only, after NFKC.
	{"title", "An Ordinary Title"},
	{"title", "  padded  "},
	{"title", ""},
	{"title", "   "},
	{"title", "-leading dash"},
	{"title", "/leading slash"},
	{"title", "café"},
	{"title", "日本語"},
	{"title", "ﬁ ligature normalises to ASCII"},
	{"title", "①"},
	{"title", "full－width hyphen normalises"},
	{"title", "tab\tinside"},
	{"title", "trailing dash-"},
}

// Length probes, built rather than written out. The limits are in characters,
// not bytes, and every one of these is non-ASCII precisely so an
// implementation that counted bytes would refuse an input Python accepts.
func lengthProbes() []struct {
	function string
	input    string
} {
	type probe = struct {
		function string
		input    string
	}
	return []probe{
		{"free", strings.Repeat("é", 4000)},
		{"free", strings.Repeat("é", 4001)},
		{"free", strings.Repeat("日", 3999)},
		{"title", strings.Repeat("a", 200)},
		{"title", strings.Repeat("a", 201)},
	}
}

type sanitizerOutcome struct {
	OK     bool   `json:"ok"`
	Value  string `json:"value"`
	Reason string `json:"reason"`
}

func TestTheSanitizersAgreeWithThePythonImplementation(t *testing.T) {
	if _, err := exec.LookPath("python3"); err != nil {
		t.Skip("python3 is unavailable, so there is nothing to compare against")
	}
	probes := append(append([]struct {
		function string
		input    string
	}{}, sanitizerProbes...), lengthProbes()...)
	inputs := make([][2]string, 0, len(probes))
	for _, probe := range probes {
		inputs = append(inputs, [2]string{probe.function, probe.input})
	}
	expected := pythonSanitizerOutcomes(t, inputs)

	for index, probe := range probes {
		name := probe.function + ": " + probe.input
		switch {
		case probe.input == "":
			name = probe.function + ": <empty>"
		case len(probe.input) > 40:
			name = fmt.Sprintf("%s: %d characters", probe.function, len([]rune(probe.input)))
		}
		t.Run(name, func(t *testing.T) {
			var value string
			var err error
			if probe.function == "free" {
				value, err = SanitizeFreeText(probe.input, "field")
			} else {
				value, err = SanitizeTitleText(probe.input, "field")
			}

			want := expected[index]
			if want.OK != (err == nil) {
				t.Fatalf("python ok=%v (%s), go ok=%v (%v)", want.OK, want.Reason, err == nil, err)
			}
			if want.OK && value != want.Value {
				t.Errorf("python returned %q, go returned %q", want.Value, value)
			}
			if !want.OK && err.Error() != want.Reason {
				t.Errorf("python refused with %q, go refused with %q", want.Reason, err.Error())
			}
		})
	}
}

// pythonSanitizerOutcomes runs every input through the Python module in one
// process, so the comparison costs one interpreter start rather than forty.
func pythonSanitizerOutcomes(t *testing.T, inputs [][2]string) []sanitizerOutcome {
	t.Helper()
	encoded, err := json.Marshal(inputs)
	if err != nil {
		t.Fatal(err)
	}
	script := `
import json, sys
from agentic_sdlc import _forge_text

results = []
for function, text in json.loads(sys.argv[1]):
    sanitize = _forge_text.sanitize_free_text if function == "free" else _forge_text.sanitize_title_text
    try:
        results.append({"ok": True, "value": sanitize(text, "field"), "reason": ""})
    except _forge_text.ForgeTextError as error:
        results.append({"ok": False, "value": "", "reason": str(error)})
print(json.dumps(results))
`
	command := exec.Command("python3", "-c", script, string(encoded))
	command.Dir = filepath.Join(repositoryRoot(t), "kernel")
	output, err := command.Output()
	if err != nil {
		t.Skipf("the Python sanitizer could not be run: %v", err)
	}
	var outcomes []sanitizerOutcome
	if err := json.Unmarshal(output, &outcomes); err != nil {
		t.Fatalf("the Python side did not return JSON: %s", output)
	}
	if len(outcomes) != len(inputs) {
		t.Fatalf("expected %d outcomes, got %d", len(inputs), len(outcomes))
	}
	return outcomes
}

func TestTheSanitizerCorpusExercisesBothOutcomes(t *testing.T) {
	// Self-vacuity. A corpus that only contained acceptable inputs would agree
	// with any implementation that accepted everything, and one that only
	// contained refusals would agree with any that refused everything.
	accepted, refused := 0, 0
	for _, probe := range append(append([]struct {
		function string
		input    string
	}{}, sanitizerProbes...), lengthProbes()...) {
		var err error
		if probe.function == "free" {
			_, err = SanitizeFreeText(probe.input, "field")
		} else {
			_, err = SanitizeTitleText(probe.input, "field")
		}
		if err == nil {
			accepted++
			continue
		}
		refused++
	}
	if accepted < 5 || refused < 5 {
		t.Errorf("the corpus accepts %d and refuses %d; it needs both in quantity",
			accepted, refused)
	}
}

func TestTaskHashIsStableAndShort(t *testing.T) {
	// The task hash marks a forge artifact as belonging to a task, and issue
	// reconciliation matches on it. A change here orphans every issue this
	// kernel has ever created.
	hash := TaskHash("TASK-1")
	if len(hash) != 16 {
		t.Errorf("TaskHash returned %d characters", len(hash))
	}
	if hash != TaskHash("TASK-1") {
		t.Error("TaskHash is not stable")
	}
	if hash == TaskHash("TASK-2") {
		t.Error("two task ids share a hash")
	}
	// Pinned against the Python implementation's value for the same input.
	if expected := hexSHA256([]byte("TASK-1"))[:16]; hash != expected {
		t.Errorf("TaskHash = %s, want %s", hash, expected)
	}
}
