package kernel

import (
	"fmt"
	"regexp"
	"strings"

	"golang.org/x/text/unicode/norm"
)

// Sanitizing the free text this kernel puts on a forge.
//
// Gate issues, status comments and reviewer nudges all carry text sourced from
// a project's own files: an applicability rationale, an authority's reason, a
// task's scope line. That text ends up in a GitHub issue or a GitLab merge
// request, where it is read by people and interpreted by the forge.
//
// The rule throughout is **reject and abort, never substitute**. A sanitizer
// that quietly rewrites its input produces a published artifact that does not
// say what the project's file says, and nobody finds out. Refusing makes the
// operator fix the source.
//
// Three classes of problem, each refused rather than escaped:
//
//   - Control and line-separator characters that render as nothing but change
//     how a line is parsed.
//   - A line beginning with "/", which several forges read as a quick action
//     -- "/close", "/assign" -- executed with the identity that posted it.
//   - A line beginning with one of this kernel's own provenance prefixes,
//     which would let project text forge the machine-generated markers a
//     reader uses to tell our content from theirs.
//
// Mentions and cross-references are the one exception, and they are
// neutralised rather than refused: an @name or a #123 in a rationale is
// ordinary prose, but posting it would notify a person or link an unrelated
// issue. A zero-width space after the sigil keeps the text readable and stops
// the forge acting on it.

var (
	labelCharset = regexp.MustCompile(`^[a-z0-9-]+$`)
	// Go's regexp has no lookbehind, so the leading non-word character is
	// captured and put back. See neutralizeReferences.
	mentionPattern  = regexp.MustCompile(`(^|[^\w])@(\w[\w.-]*)`)
	crossRefPattern = regexp.MustCompile(`(^|[^\w])([\w.-]+/[\w.-]+)?#(\d+)`)
)

// forbiddenTextRunes render as nothing, or as something other than what they
// are, while still changing how a line is read.
var forbiddenTextRunes = map[rune]bool{
	'\v': true, '\f': true, '\u001c': true, '\u001d': true, '\u001e': true,
	'\u0085': true, '\u2028': true, '\u2029': true,
}

// Reserved line prefixes. These are how a reader tells this kernel's own
// provenance lines from the text around them, so project content that begins
// with one is refused rather than published.
const (
	provenanceLine   = "> Machine-generated by agentic-sdlc."
	refLinePrefix    = "> ref "
	parentLinePrefix = "> parent "
)

var reservedPrefixes = []string{provenanceLine, refLinePrefix, parentLinePrefix}

// zeroWidthSpace separates a sigil from what follows it, so the forge stops
// recognising the reference while a reader still sees the text.
const zeroWidthSpace = "\u200b"

// TaskHash is the short, stable identifier a task's forge artifacts are marked
// with.
func TaskHash(taskID string) string {
	return hexSHA256([]byte(taskID))[:16]
}

// IsLabelCharset reports whether a label is one a forge will accept unchanged.
func IsLabelCharset(value string) bool { return labelCharset.MatchString(value) }

// SanitizeFreeText checks a free-text field and returns it with references
// neutralised, or refuses it.
func SanitizeFreeText(text, fieldName string) (string, error) {
	for _, character := range text {
		if forbiddenTextRunes[character] {
			return "", fmt.Errorf(
				"%s: contains a forbidden control/line-separator character (U+%04X)",
				fieldName, character)
		}
		if character >= 0xD800 && character <= 0xDFFF {
			return "", fmt.Errorf("%s: contains a lone Unicode surrogate", fieldName)
		}
	}
	for _, line := range splitLines(text) {
		if strings.HasPrefix(strings.TrimSpace(line), "/") {
			return "", fmt.Errorf(
				"%s: contains a line starting with '/' (forge quick-action injection risk)",
				fieldName)
		}
	}
	for _, line := range splitLines(text) {
		for _, prefix := range reservedPrefixes {
			if strings.HasPrefix(line, prefix) {
				return "", fmt.Errorf(
					"%s: contains a reserved provenance/ref/parent-line prefix", fieldName)
			}
		}
	}

	sanitized := neutralizeReferences(text)
	// Measured in characters, not bytes: the limit is about what a person
	// reads, and a rationale in a non-Latin script would otherwise be refused
	// at a quarter of the length.
	if len([]rune(sanitized)) > 4000 {
		return "", fmt.Errorf("%s: exceeds 4000 characters", fieldName)
	}
	return sanitized, nil
}

// SanitizeTitleText checks a title, which is held to a much narrower
// standard than body text.
//
// Printable ASCII only, after NFKC normalisation. A title is what a person
// scans a list of issues by, and it is also what this kernel matches on when
// reconciling an existing issue -- so a character that normalises differently
// in two places would make the same title stop matching itself.
func SanitizeTitleText(text, fieldName string) (string, error) {
	normalized := norm.NFKC.String(text)
	for _, character := range normalized {
		if character < 0x20 || character > 0x7E {
			return "", fmt.Errorf(
				"%s: contains a non-printable-ASCII character (U+%04X)", fieldName, character)
		}
	}
	stripped := strings.TrimSpace(normalized)
	if stripped == "" {
		return "", fmt.Errorf("%s: empty after normalization/strip", fieldName)
	}
	// A leading "-" reads as a flag and a leading "/" as a quick action, in
	// whichever tool eventually passes this along.
	if strings.HasPrefix(stripped, "-") || strings.HasPrefix(stripped, "/") {
		return "", fmt.Errorf("%s: must not start with '-' or '/'", fieldName)
	}
	// Characters, as above -- equal to the byte count here only because the
	// printable-ASCII check upstream guarantees it. Stated in runes so the
	// limit still means characters if that check is ever relaxed.
	if len([]rune(stripped)) > 200 {
		return "", fmt.Errorf("%s: exceeds 200 characters", fieldName)
	}
	return stripped, nil
}

// neutralizeReferences defuses mentions and cross-references.
func neutralizeReferences(text string) string {
	text = mentionPattern.ReplaceAllString(text, "${1}@"+zeroWidthSpace+"${2}")
	return crossRefPattern.ReplaceAllString(text, "${1}${2}#"+zeroWidthSpace+"${3}")
}

// splitLines splits into lines, preserving empty ones.
//
// Only \n and \r need handling here: every other terminator Python's
// str.splitlines recognises -- \v, \f, the file/group/record separators,
// NEL, and the two Unicode line/paragraph separators -- is in the forbidden
// set above and has already been refused by the time this runs. That is not a
// coincidence; the forbidden set is exactly those.
func splitLines(text string) []string {
	normalized := strings.ReplaceAll(text, "\r\n", "\n")
	normalized = strings.ReplaceAll(normalized, "\r", "\n")
	return strings.Split(normalized, "\n")
}
