package kernel

import (
	"encoding/json"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
	"testing"
)

// The configuration half of `validate`, compared against the Python kernel on
// projects the Python kernel itself created.
//
// The comparison holds only while a project has no run records. Python's
// validate does configuration *and* run records in one pass; this half does
// configuration. On a project with no runs the two must agree exactly, and
// that is the strongest statement available until the run-record half lands
// -- which is also why the subcommand stays unwired.
//
// Fixtures are generated by `agentic-sdlc init` rather than hand-written. A
// hand-written overlay agrees with whichever implementation it was written
// against; one the kernel produced agrees with neither by construction.

func pythonKernel(t *testing.T, args ...string) (int, string) {
	t.Helper()
	kernelRoot, err := filepath.Abs(filepath.Join("..", "..", "kernel"))
	if err != nil {
		t.Fatal(err)
	}
	command := exec.Command("python3", "-c",
		"import sys; from agentic_sdlc import main; sys.exit(main(sys.argv[1:]))")
	command.Args = append(command.Args, args...)
	command.Dir = kernelRoot
	output, _ := command.CombinedOutput()
	code := command.ProcessState.ExitCode()
	return code, string(output)
}

// initProject builds a fresh project overlay with the real kernel.
func initProject(t *testing.T) (root, manifest string) {
	t.Helper()
	if _, err := exec.LookPath("python3"); err != nil {
		t.Skip("python3 is unavailable, so there is nothing to compare against")
	}
	repoRoot, err := filepath.Abs(filepath.Join("..", ".."))
	if err != nil {
		t.Fatal(err)
	}
	manifest = filepath.Join(repoRoot, "provider", "provider.json")
	if _, err := os.Stat(manifest); err != nil {
		t.Skip("no provider manifest in this checkout")
	}

	root = t.TempDir()
	code, output := pythonKernel(t,
		"--provider", manifest, "init", "--root", root,
		"--profile", "secure-cloud", "--project-id", "probe")
	if code != 0 {
		t.Skipf("kernel init failed, so there is no fixture to compare: %s", truncate(output))
	}
	return root, manifest
}

func truncate(text string) string {
	if len(text) > 300 {
		return text[:300] + "..."
	}
	return text
}

// goConfiguration runs the Go configuration half.
func goConfiguration(t *testing.T, root, manifest string) ValidationReport {
	t.Helper()
	registry := NewRegistry()
	if err := registry.LoadProvider(manifest); err != nil {
		t.Fatalf("LoadProvider: %v", err)
	}
	overlay, err := LoadOverlay(root)
	if err != nil {
		t.Fatalf("LoadOverlay: %v", err)
	}
	return registry.ValidateConfiguration(root, overlay)
}

// pythonValidate runs the Python kernel's validate and parses its report.
func pythonValidate(t *testing.T, root, manifest string) ValidationReport {
	t.Helper()
	_, output := pythonKernel(t, "--provider", manifest, "validate", "--root", root)
	var report ValidationReport
	if err := json.Unmarshal([]byte(output), &report); err != nil {
		t.Fatalf("the Python kernel did not print a report: %s", truncate(output))
	}
	return report
}

func compareReports(t *testing.T, label string, python, golang ValidationReport) {
	t.Helper()
	// Sets, not sequences. Both implementations collect in their own
	// traversal order, and ordering is not a property either promises --
	// asserting it would pin an accident.
	if difference := setDifference(python.Errors, golang.Errors); len(difference) > 0 {
		t.Errorf("%s: only the Python kernel reported these errors: %v", label, difference)
	}
	if difference := setDifference(golang.Errors, python.Errors); len(difference) > 0 {
		t.Errorf("%s: only the Go kernel reported these errors: %v", label, difference)
	}
	if difference := setDifference(python.Blockers, golang.Blockers); len(difference) > 0 {
		t.Errorf("%s: only the Python kernel reported these blockers: %v", label, difference)
	}
	if difference := setDifference(golang.Blockers, python.Blockers); len(difference) > 0 {
		t.Errorf("%s: only the Go kernel reported these blockers: %v", label, difference)
	}
	if python.Valid != golang.Valid || python.Ready != golang.Ready {
		t.Errorf("%s: verdicts differ -- python valid=%v ready=%v, go valid=%v ready=%v",
			label, python.Valid, python.Ready, golang.Valid, golang.Ready)
	}
}

func setDifference(left, right []string) []string {
	present := map[string]bool{}
	for _, value := range right {
		present[value] = true
	}
	var only []string
	for _, value := range left {
		if !present[value] {
			only = append(only, value)
		}
	}
	sort.Strings(only)
	return only
}

func TestAFreshProjectIsDescribedIdentically(t *testing.T) {
	root, manifest := initProject(t)
	python := pythonValidate(t, root, manifest)
	golang := goConfiguration(t, root, manifest)

	// Self-vacuity: a freshly initialised project has real blockers -- nobody
	// has assigned authorities or confirmed commands yet. Two implementations
	// reporting nothing would agree meaninglessly.
	if len(python.Blockers) == 0 {
		t.Fatal("a fresh project reported no blockers; this comparison would prove nothing")
	}
	compareReports(t, "fresh project", python, golang)
}

func TestBrokenConfigurationsAreDescribedIdentically(t *testing.T) {
	// Each case breaks exactly one thing, so a divergence names its own cause.
	for _, probe := range []struct {
		name   string
		mutate func(t *testing.T, root string)
	}{
		{"unknown-profile", func(t *testing.T, root string) {
			mutateJSON(t, filepath.Join(root, Overlay, "project.json"), func(document map[string]any) {
				document["profile"] = "no-such-profile"
			})
		}},
		{"invalid-approval-source", func(t *testing.T, root string) {
			mutateJSON(t, filepath.Join(root, Overlay, "project.json"), func(document map[string]any) {
				document["approval_sources"] = map[string]any{"human_gate_default": "github_review"}
			})
		}},
		{"missing-authority-role", func(t *testing.T, root string) {
			mutateJSON(t, filepath.Join(root, Overlay, "authorities.json"), func(document map[string]any) {
				delete(document, "security_lead")
			})
		}},
		{"author-reviewer-overlap", func(t *testing.T, root string) {
			mutateJSON(t, filepath.Join(root, Overlay, "routing.json"), func(document map[string]any) {
				routes, _ := document["routes"].([]any)
				if len(routes) == 0 {
					t.Skip("no routes to overlap")
				}
				route := routes[0].(map[string]any)
				route["agents"] = []any{"shared-identity"}
				route["reviewers"] = []any{"shared-identity"}
			})
		}},
		{"unknown-ignored-gate", func(t *testing.T, root string) {
			mutateJSON(t, filepath.Join(root, Overlay, "routing.json"), func(document map[string]any) {
				document["ignored_gates"] = []any{"G99"}
			})
		}},
		{"wrong-kernel-lock", func(t *testing.T, root string) {
			mutateJSON(t, filepath.Join(root, Overlay, "version.lock"), func(document map[string]any) {
				document["kernel_version"] = "0.0.1"
			})
		}},
		{"unresolved-impact", func(t *testing.T, root string) {
			mutateJSON(t, filepath.Join(root, Overlay, "impact-profile.json"), func(document map[string]any) {
				document["impact_categories"] = []any{
					map[string]any{"id": "data-residency", "applicability": "unknown"},
				}
			})
		}},
	} {
		t.Run(probe.name, func(t *testing.T) {
			root, manifest := initProject(t)
			probe.mutate(t, root)

			python := pythonValidate(t, root, manifest)
			golang := goConfiguration(t, root, manifest)
			compareReports(t, probe.name, python, golang)
		})
	}
}

func TestAnAuthorReviewerOverlapIsAnErrorNotABlocker(t *testing.T) {
	// The distinction that matters most in this report. An overlap is not an
	// undecided question a human still has to answer -- it is a configuration
	// that contradicts the separation the gates exist to enforce, so it makes
	// the project invalid rather than merely not-ready.
	root, manifest := initProject(t)
	mutateJSON(t, filepath.Join(root, Overlay, "routing.json"), func(document map[string]any) {
		routes, _ := document["routes"].([]any)
		if len(routes) == 0 {
			t.Skip("no routes to overlap")
		}
		route := routes[0].(map[string]any)
		route["agents"] = []any{"shared-identity"}
		route["reviewers"] = []any{"shared-identity"}
	})

	golang := goConfiguration(t, root, manifest)
	if golang.Valid {
		t.Error("a route assigning one identity as both author and reviewer was called valid")
	}
	found := false
	for _, message := range golang.Errors {
		if strings.Contains(message, "author and reviewer") {
			found = true
		}
	}
	if !found {
		t.Errorf("the overlap was not reported as an error: %v", golang.Errors)
	}
	for _, message := range golang.Blockers {
		if strings.Contains(message, "author and reviewer") {
			t.Error("the overlap was reported as a blocker, which reads as 'decide this later'")
		}
	}
}

func mutateJSON(t *testing.T, path string, mutate func(map[string]any)) {
	t.Helper()
	raw, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("reading %s: %v", path, err)
	}
	var document map[string]any
	if err := json.Unmarshal(raw, &document); err != nil {
		t.Fatalf("parsing %s: %v", path, err)
	}
	mutate(document)
	encoded, err := json.MarshalIndent(document, "", "  ")
	if err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, encoded, 0o644); err != nil {
		t.Fatal(err)
	}
}
