package kernel

import (
	"encoding/json"
	"os/exec"
	"path/filepath"
	"sort"
	"testing"
)

// The configuration half of `validate`, compared against the Python kernel on
// projects the Python kernel itself created.
//
// The comparison holds only while a project has no run records. Python's
// validate does configuration *and* run records in one pass; this half does
// configuration. On a project with no runs the two must agree exactly, and
// that is the strongest statement available until the run-record half lands
// -- which is also why the subcommand stays unwired.
//
// Fixtures are generated by `agentic-sdlc init` rather than hand-written. A
// hand-written overlay agrees with whichever implementation it was written
// against; one the kernel produced agrees with neither by construction.

func pythonKernel(t *testing.T, args ...string) (int, string) {
	t.Helper()
	kernelRoot, err := filepath.Abs(filepath.Join("..", "..", "kernel"))
	if err != nil {
		t.Fatal(err)
	}
	return pythonKernelIn(kernelRoot, args...)
}

// pythonKernelIn runs the Python kernel from its own directory, which is how
// it finds the package it lives in without being installed.
func pythonKernelIn(kernelRoot string, args ...string) (int, string) {
	command := exec.Command("python3", "-c",
		"import sys; from agentic_sdlc import main; sys.exit(main(sys.argv[1:]))")
	command.Args = append(command.Args, args...)
	command.Dir = kernelRoot
	output, _ := command.CombinedOutput()
	return command.ProcessState.ExitCode(), string(output)
}

func pythonValidate(t *testing.T, root, manifest string) ValidationReport {
	t.Helper()
	_, output := pythonKernel(t, "--provider", manifest, "validate", "--root", root)
	var report ValidationReport
	if err := json.Unmarshal([]byte(output), &report); err != nil {
		t.Fatalf("the Python kernel did not print a report: %s", truncate(output))
	}
	return report
}

func compareReports(t *testing.T, label string, python, golang ValidationReport) {
	t.Helper()
	// Sets, not sequences. Both implementations collect in their own
	// traversal order, and ordering is not a property either promises --
	// asserting it would pin an accident.
	if difference := setDifference(python.Errors, golang.Errors); len(difference) > 0 {
		t.Errorf("%s: only the Python kernel reported these errors: %v", label, difference)
	}
	if difference := setDifference(golang.Errors, python.Errors); len(difference) > 0 {
		t.Errorf("%s: only the Go kernel reported these errors: %v", label, difference)
	}
	if difference := setDifference(python.Blockers, golang.Blockers); len(difference) > 0 {
		t.Errorf("%s: only the Python kernel reported these blockers: %v", label, difference)
	}
	if difference := setDifference(golang.Blockers, python.Blockers); len(difference) > 0 {
		t.Errorf("%s: only the Go kernel reported these blockers: %v", label, difference)
	}
	if python.Valid != golang.Valid || python.Ready != golang.Ready {
		t.Errorf("%s: verdicts differ -- python valid=%v ready=%v, go valid=%v ready=%v",
			label, python.Valid, python.Ready, golang.Valid, golang.Ready)
	}
}

func setDifference(left, right []string) []string {
	present := map[string]bool{}
	for _, value := range right {
		present[value] = true
	}
	var only []string
	for _, value := range left {
		if !present[value] {
			only = append(only, value)
		}
	}
	sort.Strings(only)
	return only
}

func TestAFreshProjectIsDescribedIdentically(t *testing.T) {
	root, manifest := initProject(t)
	python := pythonValidate(t, root, manifest)
	golang := goConfiguration(t, root, manifest)

	// Self-vacuity: a freshly initialised project has real blockers -- nobody
	// has assigned authorities or confirmed commands yet. Two implementations
	// reporting nothing would agree meaninglessly.
	if len(python.Blockers) == 0 {
		t.Fatal("a fresh project reported no blockers; this comparison would prove nothing")
	}
	compareReports(t, "fresh project", python, golang)
}

func TestBrokenConfigurationsAreDescribedIdentically(t *testing.T) {
	// Each case breaks exactly one thing, so a divergence names its own cause.
	for _, probe := range []struct {
		name   string
		mutate func(t *testing.T, root string)
	}{
		{"unknown-profile", func(t *testing.T, root string) {
			mutateJSON(t, filepath.Join(root, Overlay, "project.json"), func(document map[string]any) {
				document["profile"] = "no-such-profile"
			})
		}},
		{"invalid-approval-source", func(t *testing.T, root string) {
			mutateJSON(t, filepath.Join(root, Overlay, "project.json"), func(document map[string]any) {
				document["approval_sources"] = map[string]any{"human_gate_default": "github_review"}
			})
		}},
		{"missing-authority-role", func(t *testing.T, root string) {
			mutateJSON(t, filepath.Join(root, Overlay, "authorities.json"), func(document map[string]any) {
				delete(document, "security_lead")
			})
		}},
		{"author-reviewer-overlap", func(t *testing.T, root string) {
			mutateJSON(t, filepath.Join(root, Overlay, "routing.json"), func(document map[string]any) {
				routes, _ := document["routes"].([]any)
				if len(routes) == 0 {
					t.Skip("no routes to overlap")
				}
				route := routes[0].(map[string]any)
				route["agents"] = []any{"shared-identity"}
				route["reviewers"] = []any{"shared-identity"}
			})
		}},
		{"unknown-ignored-gate", func(t *testing.T, root string) {
			mutateJSON(t, filepath.Join(root, Overlay, "routing.json"), func(document map[string]any) {
				document["ignored_gates"] = []any{"G99"}
			})
		}},
		{"wrong-kernel-lock", func(t *testing.T, root string) {
			mutateJSON(t, filepath.Join(root, Overlay, "version.lock"), func(document map[string]any) {
				document["kernel_version"] = "0.0.1"
			})
		}},
		{"unresolved-impact", func(t *testing.T, root string) {
			mutateJSON(t, filepath.Join(root, Overlay, "impact-profile.json"), func(document map[string]any) {
				document["impact_categories"] = []any{
					map[string]any{"id": "data-residency", "applicability": "unknown"},
				}
			})
		}},
	} {
		t.Run(probe.name, func(t *testing.T) {
			root, manifest := initProject(t)
			probe.mutate(t, root)

			python := pythonValidate(t, root, manifest)
			golang := goConfiguration(t, root, manifest)
			compareReports(t, probe.name, python, golang)
		})
	}
}
