package generators

import (
	"encoding/json"
	"errors"
	"fmt"
	"io/fs"
	"os"
	"os/exec"
	"path"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"github.com/deagy/cadre/cli/internal/engine/provider"
	"github.com/deagy/cadre/cli/internal/version"
)

// Port of roster/orchestration/src/generate_global_plugin.py.
//
// The packaged plugin under plugin/ is committed, and
// .github/workflows/validate.yml's `generated-content` job runs
// `cadre generate-plugin --check --output plugin`, which fails on any byte
// difference. That makes the Python generator the specification for this file,
// not merely a reference: every string constant, ordering decision, and
// path-rewriting rule below exists to reproduce its output exactly.
//
// Structure mirrors the original deliberately (reset, then the same seven
// generator passes, then the same comparison), so a future change to one can
// be transposed to the other by inspection.

const generatedMarker = "<!-- GENERATED FILE: edit the canonical source and regenerate; do not edit this copy. -->"

// registerURL is used to rewrite packaged links whose targets exist only in
// the source repository.
const registerURL = "https://github.com/deagy/cadre"

// cliVersionPattern matches VERSION = "x.y.z" or VERSION = 'x.y.z' in cadre_cli/_version.py.
// This mirrors internal/cli/version.go's regex, reading the same marker without executing Python.
// readCLIVersion reads the Cadre CLI version, delegating to the one
// implementation of that parse. This file used to carry its own copy; when
// the marker moved from cadre_cli/_version.py to VERSION, this copy kept
// looking for the old path and `cadre generate-plugin` began failing with
// "cannot read CLI version marker" while `cadre --version` worked.
func readCLIVersion(repoRoot string) (string, error) {
	return version.Resolve(repoRoot)
}

// readKernelVersion reports the kernel release this repository targets.
//
// It used to shell out to ./cmd/agentic-sdlc --version, on the reasoning that
// parsing a constant instead would be a second reader free to drift from what
// the binary reports. That reasoning held while the kernel was built here.
// It is not, any more, and there is no in-tree binary left to drift from.
//
// So the value is a pin rather than an observation: provider.KernelVersion
// declares which kernel this repository targets, and
// TestTheKernelVersionPinSatisfiesOurOwnProvider holds it inside the window
// provider/provider.json declares. Reading it is not a boundary crossing --
// engine/provider is roster-side, like generators.
//
// The version is embedded in each lifecycle plugin'"'"'s kernel shim, which
// downloads exactly that release, so a wrong value here is a plugin that
// fetches a kernel nobody published. That risk moved rather than went away:
// it used to be a stale binary, and it is now a pin naming an unreleased
// version.
func readKernelVersion(string) (string, error) {
	if provider.KernelVersion == "" {
		return "", fmt.Errorf("no kernel version is pinned")
	}
	return provider.KernelVersion, nil
}

// providerBundle is the set of provider/ members copied verbatim into the
// package root. provider.json/profiles/extensions are hand-authored;
// agent-catalog.json and codex-agents/ are generated by
// `cadre generate-role-metadata`.
var providerBundle = []string{"provider.json", "agent-catalog.json", "profiles", "extensions", "codex-agents"}

// providerRolesDirname is the register-only member of provider/: verbatim
// copies of every role's AGENT.md, never copied into the package (the package
// reaches the same content through suite/roster/).
const providerRolesDirname = "roles"

const providerDefinitionPrefix = providerRolesDirname + "/"
const packageDefinitionPrefix = "suite/roster/"

// generatedTopLevel is everything resetGeneratedContent removes and filesEqual
// compares. Its complement is the hand-authored package assets
// (.claude-plugin/, .codex-plugin/), which carry the release version and are
// deliberately maintained by hand.
var generatedTopLevel = func() map[string]bool {
	set := map[string]bool{
		"skills": true, "agents": true, "suite": true, "bin": true,
		"README.md": true,
		// The main plugin's own PreToolUse guard, fanned out from
		// guardHookSource by generateMainPluginHook.
		"hooks": true,
	}
	for _, name := range providerBundle {
		set[name] = true
	}
	return set
}()

var lifecyclePluginDirs = []string{
	"plugins/lifecycle",
	"plugins/lifecycle-github",
	"plugins/lifecycle-gitlab",
}

// guardHookTarget is the packaged path of this repository's destructive-git
// PreToolUse guard.
//
// A selector script, not the executable: the guard ships as one compiled
// binary per platform, and something has to pick. hooks.json carries a single
// command string, so the picking happens in sh -- which is also what runs on
// Windows under Git Bash, the only way the windows binary is reachable.
const guardHookTarget = "hooks/guard"

// guardBinaryDir is where the per-platform executables are packaged, relative
// to the plugin root.
const guardBinaryDir = "hooks/bin"

func lifecycleFanout(suffix string) []string {
	out := make([]string, 0, len(lifecyclePluginDirs))
	for _, dir := range lifecyclePluginDirs {
		out = append(out, dir+"/"+suffix)
	}
	return out
}

var (
	kernelCompatibilityTargets = lifecycleFanout("tools/kernel-compatibility.json")
	lifecycleHookTargets       = lifecycleFanout("hooks/hooks.json")
	lifecycleBinTargets        = func() []string {
		var out []string
		for _, dir := range lifecyclePluginDirs {
			for _, name := range []string{"agentic-sdlc"} {
				out = append(out, dir+"/bin/"+name)
			}
		}
		return out
	}()
)

// generatedNestedPaths is generated content living *inside* an otherwise
// hand-authored top-level directory. Listed as full relative paths, not
// top-level names, so the reset and the comparison can treat exactly these
// subtrees as generated without also claiming the rest of plugins/lifecycle/
// -- or plugins/lifecycle-github/, plugins/lifecycle-gitlab/, which this
// generator never writes to at all -- is generated too.
var generatedNestedPaths = func() []string {
	out := []string{"plugins/lifecycle/skills"}
	out = append(out, kernelCompatibilityTargets...)
	out = append(out, lifecycleBinTargets...)
	out = append(out, lifecycleHookTargets...)
	return out
}()

// skillPackageTargets names the skills whose packaged home is a sub-plugin
// directory rather than the package root skills/.
var skillPackageTargets = map[string]string{
	"lifecycle-onboarding": "plugins/lifecycle/skills",
	"lifecycle-review":     "plugins/lifecycle/skills",
	"brief-pending-gates":  "plugins/lifecycle/skills",
}

// sharedPolicies are embedded into every role wrapper, in this order.
var sharedPolicies = []string{
	"roster/shared/operating-principles.md",
	"roster/shared/team-profile.yaml",
	"roster/shared/technology-standards.md",
	"roster/shared/library-standards.yaml",
	"roster/shared/knowledge-use-policy.md",
	"roster/shared/context-use-policy.md",
	"roster/shared/agent-autonomy.yaml",
	"roster/shared/documentation-style.md",
	"roster/shared/workspace-isolation.md",
}

const askHumanRule = "You are a dispatched subagent: you cannot ask the human directly. If you " +
	"reach a decision only a human can make, stop and return a clearly labeled " +
	"blocking question in your result instead of guessing or proceeding."

const sharedOverrideNote = "The shared policy content above is this package's global defaults, " +
	"embedded at packaging time. The project you are dispatched into may " +
	"extend or override them under its own `.agents/shared/`; run `cadre " +
	"resolve-shared <filename>` from that project's directory for each " +
	"shared file's effective content instead of trusting the embedded text " +
	"alone (see roster/shared/README.md in the source suite)."

// agenticSDLCShim is the kernel resolution shim placed on each lifecycle
// plugin's bin/ (Claude Code puts a plugin's bin/ on the Bash tool's PATH).
//
// It used to end in "run cadre-install-kernel", which ran bootstrap_sdlc.py,
// which created a venv and pip-installed the kernel. That kernel was Python
// and this repository deleted it (#317); the install kept working only
// because a kernel-v tag is a snapshot, so an installed plugin quietly ran a
// kernel that no longer exists here. The shim fetches the Go kernel from its
// own release instead.
//
// Downloading rather than shipping the binary, unlike the workspace guard.
// The guard fails OPEN, so a failed fetch removes protection silently and
// shipping it was the only safe answer. A missing kernel fails LOUD -- every
// `agentic-sdlc` call errors at the point of use -- so the 23MB per platform
// buys nothing here.
//
// The venv lookup is gone with the bootstrap. An existing venv install falls
// through to the download, which is the migration: the Python kernel stops
// being used without anyone having to uninstall it.
//
// The PATH search deliberately removes this script's own directory first --
// this shim *is* `agentic-sdlc` on the PATH while the plugin is enabled, so a
// plain `command -v agentic-sdlc` finds itself and re-execs forever.
func agenticSDLCShim(kernelVersion string) string {
	return strings.Join([]string{
		"#!/bin/sh",
		"set -eu",
		`BIN_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)`,
		"",
		"# Pinned at generation time, like the CLI shim's CADRE_CLI_VERSION: a",
		"# version resolved at run time would make which kernel you get depend on",
		"# when you ran it.",
		`AGENTIC_SDLC_VERSION="` + kernelVersion + `"`,
		"",
		`if [ -n "${AGENTIC_SDLC_BIN:-}" ]; then`,
		`  exec "$AGENTIC_SDLC_BIN" "$@"`,
		"fi",
		"",
		`CACHE_HOME="${XDG_CACHE_HOME:-$HOME/.cache}"`,
		`CACHE_DIR="$CACHE_HOME/cadre"`,
		`CACHED="$CACHE_DIR/agentic-sdlc-v$AGENTIC_SDLC_VERSION"`,
		"# A cached kernel is re-checked for writability before it is trusted,",
		"# the same gate the workspace guard applies to its own cache: anything",
		"# group- or other-writable is discarded and re-fetched rather than run.",
		`if [ -f "$CACHED" ] && [ -x "$CACHED" ]; then`,
		`  PERMS=$(ls -l "$CACHED" 2>/dev/null | awk '{print $1}')`,
		`  if [ "$(printf '%s' "$PERMS" | cut -c6)" != "w" ] && [ "$(printf '%s' "$PERMS" | cut -c9)" != "w" ]; then`,
		`    exec "$CACHED" "$@"`,
		"  fi",
		`  rm -f "$CACHED"`,
		"fi",
		"",
		"# Strip this shim's own directory from PATH before looking, or `command -v`",
		"# resolves back to this file and loops.",
		`CLEANED_PATH=$(printf '%s' "$PATH" | tr ':' '\n' | grep -vxF "$BIN_DIR" | paste -sd: -)`,
		`FOUND=$(PATH="$CLEANED_PATH" command -v agentic-sdlc 2>/dev/null || true)`,
		`if [ -n "$FOUND" ]; then`,
		`  exec "$FOUND" "$@"`,
		"fi",
		"",
		"# Nothing resolved: fetch the kernel this plugin was generated against.",
		"case \"$(uname -s 2>/dev/null || echo unknown)\" in",
		"  Linux)  GOOS=linux ;;",
		"  Darwin) GOOS=darwin ;;",
		"  MINGW*|MSYS*|CYGWIN*) GOOS=windows ;;",
		`  *) echo "agentic-sdlc: no kernel for this platform" >&2; exit 1 ;;`,
		"esac",
		"case \"$(uname -m 2>/dev/null || echo unknown)\" in",
		"  x86_64|amd64)  GOARCH=amd64 ;;",
		"  aarch64|arm64) GOARCH=arm64 ;;",
		`  *) echo "agentic-sdlc: no kernel for this architecture" >&2; exit 1 ;;`,
		"esac",
		"",
		`if [ "$GOOS" = "windows" ]; then`,
		`  ARCHIVE="agentic-sdlc-v$AGENTIC_SDLC_VERSION-$GOOS-$GOARCH.zip"`,
		`  MEMBER="agentic-sdlc.exe"`,
		"else",
		`  ARCHIVE="agentic-sdlc-v$AGENTIC_SDLC_VERSION-$GOOS-$GOARCH.tar.gz"`,
		`  MEMBER="agentic-sdlc"`,
		"fi",
		`BASE="https://github.com/deagy/cadre/releases/download/kernel-v$AGENTIC_SDLC_VERSION"`,
		"",
		`TEMP_DIR=$(mktemp -d) || exit 1`,
		`trap 'rm -rf "$TEMP_DIR"' EXIT`,
		"",
		"fetch() {",
		"  if command -v curl >/dev/null 2>&1; then",
		`    curl -fsSL --connect-timeout 5 --max-time 60 --proto '=https' -o "$2" "$1"`,
		"  elif command -v wget >/dev/null 2>&1; then",
		`    wget -q --timeout=5 -O "$2" "$1"`,
		"  else",
		"    return 1",
		"  fi",
		"}",
		"",
		`if ! fetch "$BASE/$ARCHIVE" "$TEMP_DIR/$ARCHIVE" || ! fetch "$BASE/SHA256SUMS" "$TEMP_DIR/SHA256SUMS"; then`,
		`  echo "agentic-sdlc: could not download the lifecycle kernel (v$AGENTIC_SDLC_VERSION). Set AGENTIC_SDLC_BIN to a kernel you already have, or install one on PATH." >&2`,
		"  exit 1",
		"fi",
		"",
		"# Verify before trusting. An unverified kernel decides gate approvals.",
		`EXPECTED=$(grep " $ARCHIVE\$" "$TEMP_DIR/SHA256SUMS" 2>/dev/null | awk '{print $1}')`,
		`if [ -z "$EXPECTED" ]; then`,
		`  echo "agentic-sdlc: $ARCHIVE is not listed in the release's SHA256SUMS" >&2`,
		"  exit 1",
		"fi",
		"if command -v sha256sum >/dev/null 2>&1; then",
		`  ACTUAL=$(sha256sum "$TEMP_DIR/$ARCHIVE" | awk '{print $1}')`,
		"elif command -v shasum >/dev/null 2>&1; then",
		`  ACTUAL=$(shasum -a 256 "$TEMP_DIR/$ARCHIVE" | awk '{print $1}')`,
		"else",
		`  echo "agentic-sdlc: no sha256 tool available to verify the download" >&2`,
		"  exit 1",
		"fi",
		`if [ "$ACTUAL" != "$EXPECTED" ]; then`,
		`  echo "agentic-sdlc: checksum mismatch on $ARCHIVE" >&2`,
		"  exit 1",
		"fi",
		"",
		`if [ "$GOOS" = "windows" ]; then`,
		`  unzip -q -o -j "$TEMP_DIR/$ARCHIVE" "$MEMBER" -d "$TEMP_DIR" || exit 1`,
		"else",
		`  tar -xzf "$TEMP_DIR/$ARCHIVE" -C "$TEMP_DIR" "$MEMBER" || exit 1`,
		"fi",
		"",
		`mkdir -p "$CACHE_DIR"`,
		`chmod 700 "$TEMP_DIR/$MEMBER"`,
		`mv "$TEMP_DIR/$MEMBER" "$CACHED"`,
		`exec "$CACHED" "$@"`,
		"",
	}, "\n")
}

// binaryShimFunctions embeds shell functions to resolve (locate or download)
// the compiled Go binary, separate from execution. Resolution suppresses noise;
// execution preserves all CLI output and exit codes. On resolution failure,
// BINARY_CACHE is set to empty, signaling fallback to Python.
var binaryShimFunctions = strings.Join([]string{
	"# Resolve a cached Go binary for the current platform, downloading if necessary.",
	"# Sets BINARY_CACHE to the path on success, or empty on failure.",
	"# All download noise is suppressed; return code signals success/failure only.",
	"try_resolve_binary() {",
	"  CACHE_DIR=\"${XDG_CACHE_HOME:-$HOME/.cache}/cadre\"",
	"  BINARY_CACHE=\"\"",
	"  ",
	"  # Determine platform from uname output.",
	"  case \"$(uname -s)\" in",
	"    Linux)  GOOS=linux ;;",
	"    Darwin) GOOS=darwin ;;",
	// This POSIX sh shim only ever runs on Windows under Git Bash, MSYS2 or
	// Cygwin, which is exactly what these uname strings identify
	// (MINGW64_NT-10.0-19045, MSYS_NT-10.0-19045, CYGWIN_NT-10.0). Without
	// them the windows/zip/cadre.exe branch below was unreachable, so the
	// windows-amd64 binary the release pipeline builds and publishes could
	// never be used by a plugin install.
	"    MINGW*|MSYS*|CYGWIN*) GOOS=windows ;;",
	"    *)      return 1 ;;  # Unsupported platform",
	"  esac",
	"  ",
	"  case \"$(uname -m)\" in",
	"    x86_64|amd64) GOARCH=amd64 ;;",
	"    aarch64|arm64) GOARCH=arm64 ;;",
	"    *)      return 1 ;;  # Unsupported architecture",
	"  esac",
	"  ",
	"  # No darwin/amd64 release. The CLI links sqlite and so needs cgo and a",
	"  # native host per platform; GitHub retired the free Intel macOS runner.",
	"  # Rosetta cannot help -- it translates x86_64 for Apple Silicon, not the",
	"  # reverse -- so this is a build-from-source platform. Said here rather",
	"  # than left to a 404 on an asset name.",
	"  if [ \"$GOOS\" = \"darwin\" ] && [ \"$GOARCH\" = \"amd64\" ]; then",
	`    echo "cadre: no release binary for Intel macOS (darwin/amd64)." >&2`,
	`    echo "  Apple Silicon is served by darwin/arm64; Rosetta does not run it on Intel." >&2`,
	`    echo "  Build from source: go build -o cadre ./cmd/cadre  (needs Go and cgo)" >&2`,
	`    echo "  Or set CADRE_BINARY to a cadre binary you already have." >&2`,
	"    return 1",
	"  fi",
	"  ",
	"  # Try to use a cached binary if it exists, is a regular file, and is executable.",
	"  CANDIDATE=\"$CACHE_DIR/cadre-v$CADRE_CLI_VERSION-$GOOS-$GOARCH\"",
	"  if [ -f \"$CANDIDATE\" ] && [ -x \"$CANDIDATE\" ]; then",
	"    # Verify the cached binary's sidecar hash, ownership, and permissions (offline, no network).",
	"    if verify_cached_binary \"$CANDIDATE\"; then",
	"      BINARY_CACHE=\"$CANDIDATE\"",
	"      return 0",
	"    fi",
	"    # Sidecar hash mismatch, ownership/permission violation, or missing sidecar:",
	"    # discard the cached binary and re-download it.",
	"    rm -f \"$CANDIDATE\" \"${CANDIDATE}.sha256\"",
	"  fi",
	"  ",
	"  # Cached binary not available or verification failed; try to download, verify, and cache it.",
	"  download_binary \"$GOOS\" \"$GOARCH\" \"$CANDIDATE\" \"$CADRE_CLI_VERSION\" || return 1",
	"  BINARY_CACHE=\"$CANDIDATE\"",
	"  return 0",
	"}",
	"",
	"# Verify a cached binary's sidecar hash and ownership.",
	"# Detects corruption, partial writes, and unprivileged tampering (offline, no network).",
	"# A process with user's UID is outside what cache-local controls can defend.",
	"# Returns 0 if valid, 1 if missing/mismatched/untrusted.",
	"verify_cached_binary() {",
	"  BINARY_PATH=\"$1\"",
	"  ",
	"  # Check that the cached binary still exists and is a regular file.",
	"  [ -f \"$BINARY_PATH\" ] || return 1",
	"  ",
	"  # Check ownership: binary must be owned by current user.",
	"  CURRENT_UID=$(id -u) || return 1",
	"  BINARY_UID=$(ls -n \"$BINARY_PATH\" 2>/dev/null | awk '{print $3}') || return 1",
	"  [ \"$CURRENT_UID\" = \"$BINARY_UID\" ] || return 1",
	"  ",
	"  # Check permissions: binary must not be writable by group (position 6) or others (position 9).",
	"  PERMS=$(ls -l \"$BINARY_PATH\" 2>/dev/null | awk '{print $1}') || return 1",
	"  # Extract group write bit (character 6) and other write bit (character 9)",
	"  GROUP_WRITE=$(echo \"$PERMS\" | cut -c6)",
	"  OTHER_WRITE=$(echo \"$PERMS\" | cut -c9)",
	"  [ \"$GROUP_WRITE\" != \"w\" ] || return 1",
	"  [ \"$OTHER_WRITE\" != \"w\" ] || return 1",
	"  ",
	"  # Check sidecar hash: read expected hash from .sha256 file (computed at cache time).",
	"  SIDECAR_PATH=\"${BINARY_PATH}.sha256\"",
	"  [ -f \"$SIDECAR_PATH\" ] || return 1",
	"  EXPECTED_HASH=$(cat \"$SIDECAR_PATH\" 2>/dev/null) || return 1",
	"  [ -n \"$EXPECTED_HASH\" ] || return 1",
	"  ",
	"  # Compute actual hash of binary and compare.",
	"  if command -v sha256sum >/dev/null 2>&1; then",
	"    ACTUAL_HASH=$(sha256sum \"$BINARY_PATH\" 2>/dev/null | awk '{print $1}')",
	"  elif command -v shasum >/dev/null 2>&1; then",
	"    ACTUAL_HASH=$(shasum -a 256 \"$BINARY_PATH\" 2>/dev/null | awk '{print $1}')",
	"  else",
	"    return 1",
	"  fi",
	"  ",
	"  [ \"$ACTUAL_HASH\" = \"$EXPECTED_HASH\" ]",
	"}",
	"",
	"# Download a release binary from GitHub, verify its checksum, and cache it.",
	"# All output is suppressed to avoid download noise.",
	"download_binary() {",
	"  GOOS=\"$1\"",
	"  GOARCH=\"$2\"",
	"  BINARY_CACHE=\"$3\"",
	"  VERSION=\"$4\"",
	"  ",
	"  # Determine archive extension based on OS.",
	"  if [ \"$GOOS\" = \"windows\" ]; then",
	"    ARCHIVE_EXT=\"zip\"",
	"    EXECUTABLE=\"cadre.exe\"",
	"  else",
	"    ARCHIVE_EXT=\"tar.gz\"",
	"    EXECUTABLE=\"cadre\"",
	"  fi",
	"  ",
	"  # Download from GitHub releases using cli-v<version> tag (not plugin-v).",
	"  ARCHIVE_NAME=\"cadre-v$VERSION-$GOOS-$GOARCH.$ARCHIVE_EXT\"",
	"  RELEASE_URL=\"https://github.com/deagy/cadre/releases/download/cli-v$VERSION/$ARCHIVE_NAME\"",
	"  SHA256SUMS_URL=\"https://github.com/deagy/cadre/releases/download/cli-v$VERSION/SHA256SUMS\"",
	"  ",
	"  # Download into a temporary location first, then verify and move.",
	"  TEMP_DIR=$(mktemp -d) || return 1",
	"  trap \"rm -rf \\\"$TEMP_DIR\\\"\" EXIT",
	"  ",
	"  ARCHIVE_PATH=\"$TEMP_DIR/$ARCHIVE_NAME\"",
	"  ",
	"  # Try to download the archive. Use curl if available, fall back to wget.",
	"  if command -v curl >/dev/null 2>&1; then",
	"    curl -fsSL --connect-timeout 5 --max-time 10 --proto '=https' -o \"$ARCHIVE_PATH\" \"$RELEASE_URL\" 2>/dev/null || return 1",
	"  elif command -v wget >/dev/null 2>&1; then",
	"    wget -q --timeout=5 -O \"$ARCHIVE_PATH\" \"$RELEASE_URL\" 2>/dev/null || return 1",
	"  else",
	"    return 1",
	"  fi",
	"  ",
	"  # Download SHA256SUMS file for verification.",
	"  SHA256SUMS_PATH=\"$TEMP_DIR/SHA256SUMS\"",
	"  if command -v curl >/dev/null 2>&1; then",
	"    curl -fsSL --connect-timeout 5 --max-time 10 --proto '=https' -o \"$SHA256SUMS_PATH\" \"$SHA256SUMS_URL\" 2>/dev/null || return 1",
	"  elif command -v wget >/dev/null 2>&1; then",
	"    wget -q --timeout=5 -O \"$SHA256SUMS_PATH\" \"$SHA256SUMS_URL\" 2>/dev/null || return 1",
	"  else",
	"    return 1",
	"  fi",
	"  ",
	"  # Verify the checksum.",
	"  EXPECTED_HASH=$(grep \"$ARCHIVE_NAME\" \"$SHA256SUMS_PATH\" 2>/dev/null | awk '{print $1}') || return 1",
	"  if [ -z \"$EXPECTED_HASH\" ]; then",
	"    return 1",
	"  fi",
	"  ",
	"  # Compute the actual hash of the downloaded archive.",
	"  if command -v sha256sum >/dev/null 2>&1; then",
	"    ACTUAL_HASH=$(sha256sum \"$ARCHIVE_PATH\" | awk '{print $1}')",
	"  elif command -v shasum >/dev/null 2>&1; then",
	"    ACTUAL_HASH=$(shasum -a 256 \"$ARCHIVE_PATH\" | awk '{print $1}')",
	"  else",
	"    return 1",
	"  fi",
	"  ",
	"  # Checksum mismatch is a failure condition.",
	"  if [ \"$ACTUAL_HASH\" != \"$EXPECTED_HASH\" ]; then",
	"    return 1",
	"  fi",
	"  ",
	"  # Extract ONLY the named executable from the archive (defense-in-depth).",
	"  # This restricts extraction to the binary we expect, ignoring other archive contents.",
	"  if [ \"$ARCHIVE_EXT\" = \"zip\" ]; then",
	"    unzip -q -o \"$ARCHIVE_PATH\" \"$EXECUTABLE\" -d \"$TEMP_DIR\" 2>/dev/null || return 1",
	"  else",
	"    tar -xzf \"$ARCHIVE_PATH\" -C \"$TEMP_DIR\" \"$EXECUTABLE\" 2>/dev/null || return 1",
	"  fi",
	"  ",
	"  EXTRACTED_BINARY=\"$TEMP_DIR/$EXECUTABLE\"",
	"  # Verify the extracted binary is a regular file, not a symlink or directory.",
	"  if [ ! -f \"$EXTRACTED_BINARY\" ] || [ -L \"$EXTRACTED_BINARY\" ]; then",
	"    return 1",
	"  fi",
	"  ",
	"  if [ ! -x \"$EXTRACTED_BINARY\" ]; then",
	"    return 1",
	"  fi",
	"  ",
	"  # Opportunistically verify the build provenance (if gh CLI is available).",
	"  # This is a defense-in-depth check; it is not required to succeed.",
	"  if command -v gh >/dev/null 2>&1; then",
	"    # Try to verify the attestation for the archive we downloaded.",
	"    ATTEST_OUT=$(gh attestation verify \"$ARCHIVE_PATH\" --repo deagy/cadre 2>&1)",
	"    if [ $? -ne 0 ] && [ -n \"$ATTEST_OUT\" ]; then",
	"      # Attestation verification failed (not missing gh): emit non-blocking note.",
	"      echo \"cadre: attestation verification failed (non-blocking)\" >&2",
	"    fi",
	"  fi",
	"  ",
	"  # Create the cache directory with restrictive permissions (mode 700).",
	"  # Use install unconditionally to enforce perms (existing 0755 dirs get tightened).",
	"  install -m 700 -d \"$CACHE_DIR\" 2>/dev/null || return 1",
	"  ",
	"  # Atomically move the binary to the cache.",
	"  BINARY_TEMP=\"$CACHE_DIR/cadre-v$VERSION-$GOOS-$GOARCH.tmp.$$\"",
	"  cp \"$EXTRACTED_BINARY\" \"$BINARY_TEMP\" || return 1",
	"  chmod +x \"$BINARY_TEMP\" || return 1",
	"  ",
	"  # H2: Reject pre-existing directory at target path (mv would move file into it).",
	"  # Clean up BINARY_TEMP on the way out: it is created and chmod +x'd above,",
	"  # so returning here without removing it leaves an executable .tmp.$$ behind",
	"  # in the cache on every collision.",
	"  if [ -d \"$BINARY_CACHE\" ]; then",
	"    rm -f \"$BINARY_TEMP\"",
	"    return 1",
	"  fi",
	"  ",
	"  if ! mv \"$BINARY_TEMP\" \"$BINARY_CACHE\" 2>/dev/null; then",
	"    rm -f \"$BINARY_TEMP\"",
	"    return 1",
	"  fi",
	"  ",
	"  # Save the binary's hash to a sidecar file for offline verification.",
	"  # On the warm path, verify_cached_binary will check this hash without network.",
	"  if command -v sha256sum >/dev/null 2>&1; then",
	"    sha256sum \"$BINARY_CACHE\" 2>/dev/null | awk '{print $1}' > \"${BINARY_CACHE}.sha256\" || true",
	"  elif command -v shasum >/dev/null 2>&1; then",
	"    shasum -a 256 \"$BINARY_CACHE\" 2>/dev/null | awk '{print $1}' > \"${BINARY_CACHE}.sha256\" || true",
	"  fi",
	"  ",
	"  return 0",
	"}",
	"",
}, "\n")

// packagedSubcommandExclusions are the bin/subcommands.tsv entries that manage
// the source repository itself and have no meaning once shipped inside the
// plugin they regenerate.
var packagedSubcommandExclusions = map[string]bool{
	"generate-plugin":          true,
	"generate-authority-aides": true,
	"generate-role-metadata":   true,
	"version":                  true,
}

// capabilityProfile is one entry of runner-capabilities.json's capability_tiers.
type capabilityProfile struct {
	Tools       []string `json:"tools"`
	SandboxMode string   `json:"sandbox_mode"`
}

// runnerCapabilities is the single source of truth for capability tiers, model
// tiers, and the reasoning efforts both runners accept. Every derived constant
// is read from the file rather than hand-duplicated, so drift between this
// package and the manifest is structurally impossible.
type runnerCapabilities struct {
	CapabilityTiers         map[string]capabilityProfile `json:"capability_tiers"`
	ModelTiers              map[string]ModelTierInfo     `json:"model_tiers"`
	AllowedReasoningEfforts []string                     `json:"allowed_reasoning_efforts"`
}

// writeCapableTiers is every capability tier whose sandbox_mode is not
// "read-only" -- i.e. every tier that can make a repository edit. Derived from
// the manifest rather than hardcoded tier names.
func (r *runnerCapabilities) writeCapableTiers() map[string]bool {
	out := map[string]bool{}
	for name, profile := range r.CapabilityTiers {
		if profile.SandboxMode != "read-only" {
			out[name] = true
		}
	}
	return out
}

// pluginGenerator holds the resolved input roots for one generation run.
type pluginGenerator struct {
	repoRoot        string
	rosterRoot      string
	skillsRoot      string
	providerRoot    string
	packagingReadme string
	guardHookSource string
	capabilities    *runnerCapabilities
	writeCapable    map[string]bool
	catalog         *orderedJSON // agent id -> map[string]string metadata
	catalogIDs      []string     // sorted agent ids
}

func newPluginGenerator(repoRoot string) (*pluginGenerator, error) {
	g := &pluginGenerator{
		repoRoot:        repoRoot,
		rosterRoot:      filepath.Join(repoRoot, "roster"),
		skillsRoot:      filepath.Join(repoRoot, ".agents", "skills"),
		providerRoot:    filepath.Join(repoRoot, "provider"),
		packagingReadme: filepath.Join(repoRoot, "packaging", "plugin-README.md"),
		guardHookSource: filepath.Join(repoRoot, "hooks"),
	}
	capabilities, err := loadRunnerCapabilities(filepath.Join(g.rosterRoot, "runner-capabilities.json"))
	if err != nil {
		return nil, err
	}
	g.capabilities = capabilities
	g.writeCapable = capabilities.writeCapableTiers()

	catalog, ids, err := g.loadCatalog(filepath.Join(g.rosterRoot, "catalog.yaml"))
	if err != nil {
		return nil, err
	}
	g.catalog = catalog
	g.catalogIDs = ids
	return g, nil
}

// newRoleContentRenderer builds a generator whose catalog comes from the
// freshly discovered role model rather than the committed catalog.yaml.
//
// `cadre generate-role-metadata` needs the same wrapper/catalog-export
// renderers as `generate-plugin`, but must render them from the role
// frontmatter it just read: rendering from the on-disk catalog.yaml instead
// would let a stale catalog make the provider bundle look current.
func newRoleContentRenderer(repoRoot string, roles []RoleMetadata) (*pluginGenerator, error) {
	g := &pluginGenerator{
		repoRoot:     repoRoot,
		rosterRoot:   filepath.Join(repoRoot, "roster"),
		skillsRoot:   filepath.Join(repoRoot, ".agents", "skills"),
		providerRoot: filepath.Join(repoRoot, "provider"),
	}
	capabilities, err := loadRunnerCapabilities(filepath.Join(g.rosterRoot, "runner-capabilities.json"))
	if err != nil {
		return nil, err
	}
	g.capabilities = capabilities
	g.writeCapable = capabilities.writeCapableTiers()

	catalog := newOrderedJSON()
	ids := make([]string, 0, len(roles))
	for _, role := range roles {
		catalog.Set(role.ID, map[string]string{
			"definition":       filepath.ToSlash(role.Definition),
			"phase":            role.Phase,
			"capability":       role.Capability,
			"model":            role.Model,
			"codex_model":      role.CodexModel,
			"reasoning_effort": role.ReasoningEffort,
		})
		ids = append(ids, role.ID)
	}
	sort.Strings(ids)
	g.catalog = catalog
	g.catalogIDs = ids
	return g, nil
}

// RenderProviderContent renders the generated members of this repository's
// provider/ bundle: agent-catalog.json, the Codex .toml wrappers under
// codex-agents/, and the verbatim role copies under roles/ that let the kernel
// resolve full role content from provider/ alone.
//
// Returned keys are absolute paths. `cadre generate-plugin` only copies
// provider/ into the package and never regenerates it, which is what lets the
// pip/pipx distribution ship it without a plugin checkout -- so these belong
// to `generate-role-metadata` and get its --check drift guard.
func RenderProviderContent(repoRoot string, roles []RoleMetadata) (map[string]string, error) {
	generator, err := newRoleContentRenderer(repoRoot, roles)
	if err != nil {
		return nil, err
	}
	providerRoot := filepath.Join(repoRoot, "provider")
	rendered := map[string]string{
		filepath.Join(providerRoot, "agent-catalog.json"): generator.agentCatalogExportContent(),
	}
	wrappers, err := generator.codexWrapperContents()
	if err != nil {
		return nil, err
	}
	for name, content := range wrappers {
		rendered[filepath.Join(providerRoot, "codex-agents", name)] = content
	}
	for _, agentID := range generator.catalogIDs {
		definition := generator.meta(agentID)["definition"]
		source, err := os.ReadFile(filepath.Join(generator.rosterRoot, filepath.FromSlash(definition)))
		if err != nil {
			return nil, fmt.Errorf("cannot read role definition %s: %w", definition, err)
		}
		rendered[filepath.Join(providerRoot, providerRolesDirname, filepath.FromSlash(definition))] = string(source)
	}
	return rendered, nil
}

func loadRunnerCapabilities(path string) (*runnerCapabilities, error) {
	content, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("%s: runner capability manifest not found", path)
	}
	var manifest runnerCapabilities
	if err := json.Unmarshal(content, &manifest); err != nil {
		return nil, fmt.Errorf("%s: invalid JSON: %w", path, err)
	}
	if manifest.CapabilityTiers == nil {
		return nil, fmt.Errorf("%s: missing required top-level key 'capability_tiers'", path)
	}
	if manifest.ModelTiers == nil {
		return nil, fmt.Errorf("%s: missing required top-level key 'model_tiers'", path)
	}
	if manifest.AllowedReasoningEfforts == nil {
		return nil, fmt.Errorf("%s: missing required top-level key 'allowed_reasoning_efforts'", path)
	}
	return &manifest, nil
}

var catalogEntryHeading = regexp.MustCompile(`^  ([a-z0-9-]+):\s*$`)

var catalogEntryFields = []string{"definition", "phase", "capability", "model", "codex_model", "reasoning_effort"}

// parseCatalogEntries parses catalog.yaml's line-oriented agent blocks into
// id -> metadata. Ported from routing.py's parse_keyed_entries(); this
// repository deliberately does not use PyYAML for these tables, and the Go
// side must agree on the same shape.
func parseCatalogEntries(content string) (*orderedJSON, error) {
	entries := newOrderedJSON()
	current := ""
	for number, line := range pySplitLines(content) {
		if match := catalogEntryHeading.FindStringSubmatch(line); match != nil {
			current = match[1]
			if _, exists := entries.Get(current); exists {
				return nil, fmt.Errorf("line %d: duplicate id %q", number+1, current)
			}
			entries.Set(current, map[string]string{})
			continue
		}
		if current == "" {
			continue
		}
		trimmed := strings.TrimSpace(line)
		for _, field := range catalogEntryFields {
			if !strings.HasPrefix(trimmed, field+":") {
				continue
			}
			key, value, _ := strings.Cut(trimmed, ":")
			raw, _ := entries.Get(current)
			raw.(map[string]string)[key] = strings.TrimSpace(value)
			break
		}
	}
	return entries, nil
}

func (g *pluginGenerator) loadCatalog(path string) (*orderedJSON, []string, error) {
	content, err := os.ReadFile(path)
	if err != nil {
		return nil, nil, fmt.Errorf("cannot read catalog.yaml: %w", err)
	}
	agents, err := parseCatalogEntries(string(content))
	if err != nil {
		return nil, nil, err
	}
	if len(agents.Keys()) == 0 {
		return nil, nil, errors.New("no agents found in catalog.yaml")
	}

	allowedCodexModels := map[string]bool{}
	for _, tier := range g.capabilities.ModelTiers {
		allowedCodexModels[tier.CodexModel] = true
	}
	allowedEfforts := map[string]bool{}
	for _, effort := range g.capabilities.AllowedReasoningEfforts {
		allowedEfforts[effort] = true
	}

	for _, agentID := range agents.Keys() {
		raw, _ := agents.Get(agentID)
		metadata := raw.(map[string]string)
		if _, ok := g.capabilities.CapabilityTiers[metadata["capability"]]; !ok {
			return nil, nil, fmt.Errorf("agent %s must declare one of: %s",
				agentID, strings.Join(sortedKeysOfProfiles(g.capabilities.CapabilityTiers), ", "))
		}
		if model, ok := metadata["model"]; ok {
			if _, known := g.capabilities.ModelTiers[model]; !known {
				return nil, nil, fmt.Errorf("agent %s declares an unsupported model tier %q", agentID, model)
			}
		}
		if codexModel, ok := metadata["codex_model"]; ok && !allowedCodexModels[codexModel] {
			return nil, nil, fmt.Errorf("agent %s declares an unsupported codex_model %q", agentID, codexModel)
		}
		if effort, ok := metadata["reasoning_effort"]; ok && !allowedEfforts[effort] {
			return nil, nil, fmt.Errorf("agent %s declares an unsupported reasoning_effort %q", agentID, effort)
		}
	}

	ids := append([]string(nil), agents.Keys()...)
	sort.Strings(ids)
	return agents, ids, nil
}

func sortedKeysOfProfiles(profiles map[string]capabilityProfile) []string {
	out := make([]string, 0, len(profiles))
	for name := range profiles {
		out = append(out, name)
	}
	sort.Strings(out)
	return out
}

func (g *pluginGenerator) meta(agentID string) map[string]string {
	raw, _ := g.catalog.Get(agentID)
	return raw.(map[string]string)
}

// ---------------------------------------------------------------------------
// Role wrapper content, shared by both runners.
// ---------------------------------------------------------------------------

type roleWrapperInputs struct {
	definition      string
	description     string
	profile         capabilityProfile
	model           string
	codexModel      string
	reasoningEffort string
	instructions    string
}

// roleWrapperInputs is the wrapper content both runners derive from one role.
// generateAgentWrappers (Claude Code, package-only) and codexWrapperContents
// (Codex, register-side under provider/) write to different trees but must
// embed byte-identical role and shared-policy instructions.
func (g *pluginGenerator) roleWrapperInputs(agentID string) (*roleWrapperInputs, error) {
	metadata := g.meta(agentID)
	definition := metadata["definition"]
	phase := metadata["phase"]
	if phase == "" {
		phase = "unknown"
	}
	capability := metadata["capability"]
	profile := g.capabilities.CapabilityTiers[capability]

	loadPolicySections := func(relatives []string) ([]string, error) {
		// Shared policy files are optional: a project (or this repository) may
		// not have every one of them, or may have emptied one, and neither
		// state is a defect. Skip missing or emptied files rather than failing,
		// and don't leave a stray blank section behind.
		var sections []string
		for _, relative := range relatives {
			raw, err := os.ReadFile(filepath.Join(g.repoRoot, filepath.FromSlash(relative)))
			if err != nil {
				continue
			}
			body := strings.TrimSpace(string(raw))
			if body == "" {
				continue
			}
			if _, universal := universalPolicySections[relative]; universal && !g.writeCapable[capability] {
				excerpt, err := excerptUniversalSections(relative, body)
				if err != nil {
					return nil, err
				}
				body = excerpt
			}
			sections = append(sections, fmt.Sprintf("# Shared policy: %s\n\n%s", relative, body))
		}
		return sections, nil
	}

	sharedSections, err := loadPolicySections(sharedPolicies)
	if err != nil {
		return nil, err
	}
	// TIER_SCOPED_POLICIES is currently empty upstream; the mechanism is kept
	// there because the tier-gating question recurs. Nothing to append here.
	sharedContent := strings.Join(sharedSections, "\n\n")

	// A migrated role's AGENT.md carries `---`-delimited frontmatter ahead of
	// its prose body; that frontmatter is generated-file bookkeeping for
	// catalog.yaml/routing.json, not role instructions, so it must never be
	// embedded into the wrapper.
	rawRole, err := os.ReadFile(filepath.Join(g.rosterRoot, filepath.FromSlash(definition)))
	if err != nil {
		return nil, fmt.Errorf("cannot read role definition %s: %w", definition, err)
	}
	stripped, err := StripFrontmatter(string(rawRole))
	if err != nil {
		return nil, fmt.Errorf("%s: %w", definition, err)
	}
	roleBody := strings.TrimSpace(stripped)

	parts := []string{fmt.Sprintf("# Role: %s\n\n%s", agentID, roleBody)}
	if sharedContent != "" {
		parts = append(parts, sharedContent)
	}
	parts = append(parts, sharedOverrideNote, askHumanRule)

	return &roleWrapperInputs{
		definition:      definition,
		description:     fmt.Sprintf("Secure cloud agent suite role for the %s phase (%s).", phase, agentID),
		profile:         profile,
		model:           metadata["model"],
		codexModel:      metadata["codex_model"],
		reasoningEffort: metadata["reasoning_effort"],
		instructions:    strings.Join(parts, "\n\n"),
	}, nil
}

// generateAgentWrappers writes the Claude Code plugin-bundled subagent
// wrappers. Package-only: Claude Code auto-discovers these from the installed
// plugin's agents/ directory, so they have no meaning outside it.
func (g *pluginGenerator) generateAgentWrappers(pluginRoot string) ([]string, error) {
	var written []string
	for _, agentID := range g.catalogIDs {
		inputs, err := g.roleWrapperInputs(agentID)
		if err != nil {
			return nil, err
		}
		lines := []string{
			"---",
			"name: " + agentID,
			"description: " + inputs.description,
			"tools: " + strings.Join(inputs.profile.Tools, ", "),
		}
		if inputs.model != "" {
			lines = append(lines, "model: "+inputs.model)
		}
		if inputs.reasoningEffort != "" {
			lines = append(lines, "effort: "+inputs.reasoningEffort)
		}
		lines = append(lines,
			"generated: true",
			"canonical_source: roster/"+inputs.definition,
			"---",
			"",
			inputs.instructions,
			"",
		)
		target := filepath.Join(pluginRoot, "agents", agentID+".md")
		if err := writeFile(target, strings.Join(lines, "\n")); err != nil {
			return nil, err
		}
		written = append(written, target)
	}
	return written, nil
}

// codexWrapperContents renders the Codex role wrappers as {filename: content},
// for provider/codex-agents/. Codex discovers custom agents only from
// ~/.codex/agents/ or a project's .codex/agents/, never from a plugin
// manifest, so these are a tracked staging copy that `cadre bootstrap-codex`
// installs from. This generator only needs them to detect a stale provider/.
func (g *pluginGenerator) codexWrapperContents() (map[string]string, error) {
	contents := map[string]string{}
	for _, agentID := range g.catalogIDs {
		inputs, err := g.roleWrapperInputs(agentID)
		if err != nil {
			return nil, err
		}
		// `model` uses catalog.yaml's separate `codex_model` OpenAI identifier,
		// not the Claude Code wrapper's haiku/sonnet/opus tier name -- the two
		// runners don't share a model-naming space.
		codexAgentID := "agents-" + agentID
		lines := []string{
			"# GENERATED FILE: canonical source is roster/" + inputs.definition,
			"name = " + pyJSONString(codexAgentID),
			"description = " + pyJSONString(inputs.description),
			"sandbox_mode = " + pyJSONString(inputs.profile.SandboxMode),
		}
		if inputs.codexModel != "" {
			lines = append(lines, "model = "+pyJSONString(inputs.codexModel))
		}
		if inputs.reasoningEffort != "" {
			lines = append(lines, "model_reasoning_effort = "+pyJSONString(inputs.reasoningEffort))
		}
		lines = append(lines,
			"developer_instructions = "+pyJSONString(inputs.instructions),
			"",
		)
		contents[codexAgentID+".toml"] = strings.Join(lines, "\n")
	}
	return contents, nil
}

func deriveKind(definition string) string {
	if strings.HasPrefix(definition, "review/") || definition == "engineering/test-engineer/AGENT.md" {
		return "reviewer"
	}
	if strings.HasPrefix(definition, "support/") {
		return "specialist"
	}
	if definition == "documentation/evidence-curator/AGENT.md" || definition == "knowledge-store/AGENT.md" {
		return "specialist"
	}
	return "author"
}

// agentCatalogExportContent renders the package-relative catalog export
// consumed through provider.json. Written into this repository's own provider/
// bundle by `cadre generate-role-metadata`; reproduced here only to detect a
// stale provider/ before packaging it.
func (g *pluginGenerator) agentCatalogExportContent() string {
	agents := newOrderedJSON()
	for _, agentID := range g.catalogIDs {
		metadata := g.meta(agentID)
		phase := metadata["phase"]
		if phase == "" {
			phase = "unknown"
		}
		kind := deriveKind(metadata["definition"])
		capabilities := []string{"author", "dispatch"}
		if kind == "reviewer" {
			capabilities = []string{"reviewer"}
		}
		agents.Set(agentID, newOrderedJSON().
			Set("phase", phase).
			Set("kind", kind).
			Set("capabilities", capabilities).
			Set("definition", providerDefinitionPrefix+metadata["definition"]))
	}
	root := newOrderedJSON().Set("schema_version", 1).Set("agents", agents)
	return pyJSONDumps(root, 0) + "\n"
}

// ---------------------------------------------------------------------------
// Reset.
// ---------------------------------------------------------------------------

// resetGeneratedContent removes exactly the generated set before regenerating.
// Derived from generatedTopLevel rather than re-listed, so a new member can
// never be generated-but-not-reset (which would leave stale files that
// filesEqual then reports as drift forever, with no way to regenerate out of
// it). bin/ is the one entry not removed wholesale: only bin/cadre is
// generated, and the directory may legitimately hold nothing else. README.md
// is the one entry that may need to survive too, when removeReadme is false.
func resetGeneratedContent(pluginRoot string, removeReadme bool) error {
	names := make([]string, 0, len(generatedTopLevel))
	for name := range generatedTopLevel {
		if name == "bin" {
			continue
		}
		names = append(names, name)
	}
	sort.Strings(names)
	for _, name := range names {
		if name == "README.md" && !removeReadme {
			continue
		}
		if err := os.RemoveAll(filepath.Join(pluginRoot, name)); err != nil {
			return err
		}
	}
	if err := os.RemoveAll(filepath.Join(pluginRoot, "bin", "cadre")); err != nil {
		return err
	}
	// Nested generated content: reset only the generated subtree itself, never
	// its hand-authored siblings -- e.g. plugins/lifecycle/skills/ is removed
	// and regenerated, but plugins/lifecycle/.claude-plugin/, .codex-plugin/,
	// and tools/ (the plugin's own manifests and bootstrap tooling) survive.
	for _, relative := range generatedNestedPaths {
		if err := os.RemoveAll(filepath.Join(pluginRoot, filepath.FromSlash(relative))); err != nil {
			return err
		}
	}
	return nil
}

// ---------------------------------------------------------------------------
// Provider bundle.
// ---------------------------------------------------------------------------

// generateProviderCopy copies this repository's provider/ bundle into the
// package root. The bundle is register-owned: the package receives a verbatim
// copy so an installed plugin carries its own provider contracts, and
// filesEqual then fails the drift check if the package's copy ever diverges.
func (g *pluginGenerator) generateProviderCopy(pluginRoot string) ([]string, error) {
	// The generated members of provider/ are produced by
	// `cadre generate-role-metadata`, not here, so this generator can only copy
	// whatever the register last committed. Editing a role's AGENT.md and
	// running generate-plugin alone would refresh the package's Claude Code
	// wrappers (built live from the catalog) while silently packaging stale
	// Codex wrappers and a stale catalog export -- and a following --check,
	// which compares package against the same stale register content, would
	// call it current. Fail loudly instead.
	expected := map[string]string{"agent-catalog.json": g.agentCatalogExportContent()}
	codexWrappers, err := g.codexWrapperContents()
	if err != nil {
		return nil, err
	}
	for name, body := range codexWrappers {
		expected["codex-agents/"+name] = body
	}
	var stale []string
	for relative, want := range expected {
		actual, err := os.ReadFile(filepath.Join(g.providerRoot, filepath.FromSlash(relative)))
		if err != nil || string(actual) != want {
			stale = append(stale, filepath.Join(g.providerRoot, filepath.FromSlash(relative)))
		}
	}
	if len(stale) > 0 {
		sort.Strings(stale)
		shown := stale
		suffix := ""
		if len(shown) > 5 {
			shown = shown[:5]
			suffix = " ..."
		}
		return nil, fmt.Errorf(
			"provider/ is stale; run `cadre generate-role-metadata` before regenerating the package: %s%s",
			strings.Join(shown, ", "), suffix)
	}

	var written []string
	for _, name := range providerBundle {
		source := filepath.Join(g.providerRoot, name)
		info, err := os.Lstat(source)
		if err != nil {
			return nil, fmt.Errorf(
				"%s: missing from the provider bundle; run `cadre generate-role-metadata` if it is generated content",
				source)
		}
		target := filepath.Join(pluginRoot, name)
		switch {
		case info.IsDir():
			// Dereferencing a symlink would silently vendor out-of-tree content
			// into a published package; refuse instead.
			copied, err := copyTree(source, target)
			if err != nil {
				return nil, err
			}
			written = append(written, copied...)
		case name == "agent-catalog.json":
			// Re-point `definition` from the register's provider/roles/ tree to
			// the package's own suite/roster/ copy of the same files. The kernel
			// resolves these relative to whichever copy it reads and rejects
			// escapes, so the two trees genuinely need different spellings.
			rewritten, err := rewriteAgentCatalog(source)
			if err != nil {
				return nil, err
			}
			if err := writeFile(target, rewritten); err != nil {
				return nil, err
			}
			written = append(written, target)
		default:
			if err := copyFile(source, target); err != nil {
				return nil, err
			}
			written = append(written, target)
		}
	}
	return written, nil
}

// rewriteAgentCatalog reads the register's agent-catalog.json and re-points
// each `definition` at the package's suite/roster/ copy, re-serialized with
// Python's json.dumps(indent=2) formatting.
func rewriteAgentCatalog(source string) (string, error) {
	raw, err := os.ReadFile(source)
	if err != nil {
		return "", err
	}
	parsed, err := parseOrderedJSON(raw)
	if err != nil {
		return "", fmt.Errorf("%s: %w", source, err)
	}
	agentsAny, ok := parsed.Get("agents")
	if !ok {
		return "", fmt.Errorf("%s: missing 'agents'", source)
	}
	agents, ok := agentsAny.(*orderedJSON)
	if !ok {
		return "", fmt.Errorf("%s: 'agents' is not an object", source)
	}
	for _, agentID := range agents.Keys() {
		entryAny, _ := agents.Get(agentID)
		entry, ok := entryAny.(*orderedJSON)
		if !ok {
			return "", fmt.Errorf("%s: agent %q is not an object", source, agentID)
		}
		definitionAny, _ := entry.Get("definition")
		definition, _ := definitionAny.(string)
		if !strings.HasPrefix(definition, providerDefinitionPrefix) {
			return "", fmt.Errorf(
				"%s: definition %q does not start with %q; run `cadre generate-role-metadata`",
				source, definition, providerDefinitionPrefix)
		}
		entry.Set("definition", packageDefinitionPrefix+definition[len(providerDefinitionPrefix):])
	}
	return pyJSONDumps(parsed, 0) + "\n", nil
}

// ---------------------------------------------------------------------------
// Skills.
// ---------------------------------------------------------------------------

func (g *pluginGenerator) generateSkillCopies(pluginRoot string) ([]string, error) {
	tracked, err := gitTrackedFiles(g.repoRoot, ".agents/skills")
	if err != nil {
		return nil, err
	}
	entries, err := os.ReadDir(g.skillsRoot)
	if err != nil {
		return nil, fmt.Errorf("cannot read %s: %w", g.skillsRoot, err)
	}
	var skillNames []string
	for _, entry := range entries {
		if entry.IsDir() {
			skillNames = append(skillNames, entry.Name())
		}
	}
	sort.Strings(skillNames)

	var written []string
	for _, name := range skillNames {
		skillDir := filepath.Join(g.skillsRoot, name)
		if info, err := os.Stat(filepath.Join(skillDir, "SKILL.md")); err != nil || info.IsDir() {
			continue
		}
		packageRoot := "skills"
		if override, ok := skillPackageTargets[name]; ok {
			packageRoot = override
		}
		targetDir := filepath.Join(pluginRoot, filepath.FromSlash(packageRoot), name)

		prefix := ".agents/skills/" + name + "/"
		var members []string
		for _, relative := range tracked {
			if strings.HasPrefix(relative, prefix) {
				members = append(members, relative)
			}
		}
		sort.Strings(members)
		for _, relative := range members {
			source := filepath.Join(g.repoRoot, filepath.FromSlash(relative))
			if info, err := os.Lstat(source); err == nil && info.Mode()&os.ModeSymlink != 0 {
				return nil, fmt.Errorf("symlinks are not allowed in packaged skills: %s", relative)
			}
			target := filepath.Join(targetDir, filepath.FromSlash(strings.TrimPrefix(relative, prefix)))
			if err := copyFile(source, target); err != nil {
				return nil, err
			}
		}

		// target_dir sits packageRoot's depth + 1 (the skill's own directory)
		// below pluginRoot -- "skills/<name>/" is 2 levels down,
		// "plugins/lifecycle/skills/<name>/" is 4. Computed rather than
		// hardcoded so a skillPackageTargets entry can never ship a wrong hint.
		upLevels := strings.Repeat("../", len(strings.Split(packageRoot, "/"))+1)
		upLevels = strings.TrimSuffix(upLevels, "/")
		packageNote := "\n\n> Packaged suite note: when the current project has no local `roster/` " +
			"tree, resolve suite files under `" + upLevels + "/suite/roster/` relative to this " +
			"`SKILL.md`. The packaged plugin is self-contained; do not look for the " +
			"source checkout.\n"

		skillTarget := filepath.Join(targetDir, "SKILL.md")
		raw, err := os.ReadFile(skillTarget)
		if err != nil {
			return nil, fmt.Errorf("cannot read packaged skill %s: %w", skillTarget, err)
		}
		content := string(raw)
		// Deliberately the same raw substring search the Python does
		// (content.find("---", 3) + 3), not the exact-line frontmatter helper:
		// SKILL.md frontmatter is written by hand and the two have never
		// disagreed, and changing it here would silently move the note.
		offset := strings.Index(content[3:], "---")
		if offset < 0 {
			return nil, fmt.Errorf("%s: no closing frontmatter delimiter", skillTarget)
		}
		frontmatterEnd := offset + 3 + 3
		if err := writeFile(skillTarget, content[:frontmatterEnd]+packageNote+content[frontmatterEnd:]); err != nil {
			return nil, err
		}

		files, err := listFiles(targetDir)
		if err != nil {
			return nil, err
		}
		written = append(written, files...)
	}
	return written, nil
}

// ---------------------------------------------------------------------------
// Lifecycle plugin fan-out.
// ---------------------------------------------------------------------------

// generateKernelCompatibility ships the kernel compatibility window, the
// bootstrap script, the SessionStart hook, the install skill, and the two bin
// shims into each lifecycle plugin.
//
// The window is derived from provider.json rather than copied wholesale: the
// bootstrap only needs {minimum, maximum_exclusive}, and provider.json also
// carries an unrelated `version` field that has been mistaken for the kernel
// range before.
func (g *pluginGenerator) generateKernelCompatibility(pluginRoot string) ([]string, error) {
	manifest, err := g.providerManifest()
	if err != nil {
		return nil, err
	}
	compatibilityAny, ok := manifest.Get("kernel_compatibility")
	if !ok {
		return nil, fmt.Errorf("provider.json: missing kernel_compatibility")
	}
	compatibility, ok := compatibilityAny.(*orderedJSON)
	if !ok {
		return nil, fmt.Errorf("provider.json: kernel_compatibility is not an object")
	}
	minimum, _ := compatibility.Get("minimum")
	maximum, _ := compatibility.Get("maximum_exclusive")
	payload := newOrderedJSON().
		Set("_comment", "Generated from provider.json's kernel_compatibility by "+
			"cadre generate-plugin. Do not hand-edit; edit provider/provider.json "+
			"and regenerate.").
		Set("minimum", minimum).
		Set("maximum_exclusive", maximum)
	payloadText := pyJSONDumps(payload, 0) + "\n"

	var written []string
	for _, relative := range kernelCompatibilityTargets {
		target := filepath.Join(pluginRoot, filepath.FromSlash(relative))
		if err := writeFile(target, payloadText); err != nil {
			return nil, err
		}
		written = append(written, target)
	}

	hooksJSON := pyJSONDumps(lifecycleHooks(), 0) + "\n"
	for _, relative := range lifecycleHookTargets {
		target := filepath.Join(pluginRoot, filepath.FromSlash(relative))
		if err := writeFile(target, hooksJSON); err != nil {
			return nil, err
		}
		written = append(written, target)
	}

	kernelVersion, err := readKernelVersion(g.repoRoot)
	if err != nil {
		return nil, err
	}
	for _, relative := range lifecycleBinTargets {
		target := filepath.Join(pluginRoot, filepath.FromSlash(relative))
		if err := writeFile(target, agenticSDLCShim(kernelVersion)); err != nil {
			return nil, err
		}
		// Useless without the executable bit: Claude Code adds bin/ to PATH but
		// does not chmod anything.
		if err := os.Chmod(target, 0o755); err != nil { //nolint:gosec // intentionally executable
			return nil, err
		}
		written = append(written, target)
	}
	return written, nil
}

// lifecycleHooks is the SessionStart detect-and-report hook. It runs before the
// human has asked for anything, on every session start, so it must not
// install, must not write, and must not fail.
func lifecycleHooks() *orderedJSON {
	entry := newOrderedJSON().
		Set("type", "command").
		Set("command", `"${CLAUDE_PLUGIN_ROOT}/bin/cadre-install-kernel" --check`).
		// A hook that stalls degrades every session start for a problem that is
		// at worst "one optional feature is not set up yet".
		Set("timeout", 15)
	group := newOrderedJSON().Set("hooks", []any{entry})
	return newOrderedJSON().Set("hooks", newOrderedJSON().Set("SessionStart", []any{group}))
}

// mainPluginHooks wires the packaged destructive-git guard. The command line
// mirrors this repository's own .claude/settings.json exactly, substituting
// ${CLAUDE_PLUGIN_ROOT} for ${CLAUDE_PROJECT_DIR}.
func mainPluginHooks() *orderedJSON {
	entry := newOrderedJSON().
		Set("type", "command").
		Set("command", `"${CLAUDE_PLUGIN_ROOT}/`+guardHookTarget+`"`)
	matcher := newOrderedJSON().
		Set("matcher", "Bash").
		Set("hooks", []any{entry})
	return newOrderedJSON().Set("hooks", newOrderedJSON().Set("PreToolUse", []any{matcher}))
}

// generateMainPluginHook packages this repository's own destructive-git
// PreToolUse guard into the main `cadre` plugin, so any project that installs
// the plugin gets the same structural protection this repository runs on
// itself, without needing the separate cadre-lifecycle-* plugins.
func (g *pluginGenerator) generateMainPluginHook(pluginRoot string) ([]string, error) {
	written := []string{}

	// The selector, then every platform binary it can reach. Copied rather
	// than built: `generate-plugin --check` compares committed output against
	// a fresh run, and a rebuilt binary is only byte-identical when the Go
	// toolchain matches, which would make the drift guard fail for a reason
	// that has nothing to do with drift. The binaries are committed under
	// hooks/bin and refreshed by `make guard-binaries`;
	// TestTheCommittedGuardBinaryMatchesTheSource checks they are current by
	// running one, not by comparing bytes.
	guardTarget := filepath.Join(pluginRoot, filepath.FromSlash(guardHookTarget))
	if err := copyFile(filepath.Join(g.guardHookSource, "guard"), guardTarget); err != nil {
		return nil, err
	}
	written = append(written, guardTarget)

	binaries, err := os.ReadDir(filepath.Join(g.guardHookSource, "bin"))
	if err != nil {
		return nil, fmt.Errorf("the guard binaries are missing (%w) -- run `make guard-binaries`", err)
	}
	copied := 0
	for _, entry := range binaries {
		if entry.IsDir() || !strings.HasPrefix(entry.Name(), "cadre-guard-") {
			continue
		}
		target := filepath.Join(pluginRoot, filepath.FromSlash(guardBinaryDir), entry.Name())
		if err := copyFile(filepath.Join(g.guardHookSource, "bin", entry.Name()), target); err != nil {
			return nil, err
		}
		written = append(written, target)
		copied++
	}
	if copied == 0 {
		// A plugin whose hook resolves to nothing is a plugin with no guard,
		// and the guard fails open, so nothing downstream would report it.
		return nil, fmt.Errorf("no guard binaries found under %s -- run `make guard-binaries`",
			filepath.Join(g.guardHookSource, "bin"))
	}

	hooksTarget := filepath.Join(pluginRoot, "hooks", "hooks.json")
	if err := writeFile(hooksTarget, pyJSONDumps(mainPluginHooks(), 0)+"\n"); err != nil {
		return nil, err
	}
	return append(written, hooksTarget), nil
}

// ---------------------------------------------------------------------------
// Packaged launcher.
// ---------------------------------------------------------------------------

type subcommandRow struct {
	name        string
	description string
}

func loadSubcommandTable(repoRoot string) ([]subcommandRow, error) {
	raw, err := os.ReadFile(filepath.Join(repoRoot, "bin", "subcommands.tsv"))
	if err != nil {
		return nil, err
	}
	var rows []subcommandRow
	for _, line := range pySplitLines(string(raw)) {
		if line == "" {
			continue
		}
		fields := strings.Split(line, "\t")
		if len(fields) != 2 {
			return nil, fmt.Errorf("bin/subcommands.tsv: expected 2 tab-separated columns, got %d: %q",
				len(fields), line)
		}
		rows = append(rows, subcommandRow{fields[0], fields[1]})
	}
	return rows, nil
}

// packagedSubcommands is the set of bin/subcommands.tsv entries the packaged
// plugin serves. It no longer maps each to a script path: the wrapper execs
// the Go binary and lets it dispatch, rather than emitting a case arm per
// subcommand pointing at a Python file.
func packagedSubcommands(repoRoot string) ([]subcommandRow, error) {
	rows, err := loadSubcommandTable(repoRoot)
	if err != nil {
		return nil, err
	}
	var out []subcommandRow
	for _, row := range rows {
		if packagedSubcommandExclusions[row.name] {
			continue
		}
		out = append(out, row)
	}
	return out, nil
}

func (g *pluginGenerator) providerManifest() (*orderedJSON, error) {
	raw, err := os.ReadFile(filepath.Join(g.providerRoot, "provider.json"))
	if err != nil {
		return nil, fmt.Errorf("cannot read provider.json: %w", err)
	}
	return parseOrderedJSON(raw)
}

// kernelRequirementText interpolates the declared kernel range into the
// generated launcher. The launcher is POSIX sh with no JSON parser, so it
// cannot read provider.json at runtime; resolve it here instead. Do not
// hardcode a version -- provider.json's own `version` and its
// `kernel_compatibility` are different version lines.
func (g *pluginGenerator) kernelRequirementText() string {
	manifest, err := g.providerManifest()
	if err != nil {
		return "a compatible version"
	}
	compatibilityAny, ok := manifest.Get("kernel_compatibility")
	if !ok {
		return "a compatible version"
	}
	compatibility, ok := compatibilityAny.(*orderedJSON)
	if !ok {
		return "a compatible version"
	}
	minimumAny, ok := compatibility.Get("minimum")
	if !ok {
		return "a compatible version"
	}
	minimum, ok := minimumAny.(string)
	if !ok {
		return "a compatible version"
	}
	return "v" + minimum + "+"
}

func (g *pluginGenerator) generateBinWrapper(pluginRoot string) (string, error) {
	// Read the CLI version for binary download URL construction.
	// This is embedded at generation time and pinned for reproducibility and offline safety.
	cliVersion, err := readCLIVersion(g.repoRoot)
	if err != nil {
		return "", fmt.Errorf("cannot read CLI version: %w", err)
	}

	rows, err := packagedSubcommands(g.repoRoot)
	if err != nil {
		return "", err
	}
	// The wrapper no longer emits a per-subcommand case block: it execs the
	// binary, which dispatches every subcommand itself. rows is still read so
	// a malformed subcommands.tsv fails generation rather than silently
	// producing a wrapper for a table nobody validated.
	names := make([]string, 0, len(rows)+1)
	for _, row := range rows {
		names = append(names, row.name)
	}
	// names/usage are no longer emitted: the binary owns its own help text,
	// so the wrapper does not carry a second copy that can drift from it.
	_ = names

	body := []string{
		"#!/bin/sh",
		"set -eu",
		`BIN_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)`,
		`PLUGIN_ROOT=$(CDPATH= cd -- "$BIN_DIR/.." && pwd)`,
		`SUITE_ROOT="$PLUGIN_ROOT/suite"`,
		`if [ "${1:-}" = "--interactive" ]; then`,
		"  CADRE_INTERACTIVE=1",
		"  export CADRE_INTERACTIVE",
		"  shift",
		"fi",
		`command_name="${1:-help}"`,
		`[ "$#" -gt 0 ] && shift || true`,
		// Release automation updates the hand-authored plugin manifests without
		// regenerating this wrapper. Read its package-local manifest at
		// invocation time, rather than baking a copy of that
		// independently-versioned value into generated content.
		`if [ "$command_name" = "--version" ] && [ "$#" -eq 0 ]; then`,
		`  plugin_version=$(sed -n 's/^[[:space:]]*"version"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' "$PLUGIN_ROOT/.claude-plugin/plugin.json")`,
		`  [ -n "$plugin_version" ] || { echo "cadre: could not read plugin version from .claude-plugin/plugin.json" >&2; exit 1; }`,
		`  printf 'cadre %s\n' "$plugin_version"`,
		`  exit 0`,
		`fi`,
		"",
		"# Resolve the compiled binary. Every dispatch path below needs it.",
	}
	// Append binary shim functions as individual lines.
	body = append(body, strings.Split(binaryShimFunctions, "\n")...)
	body = append(body,
		"# Plugin version for --version flag (read at runtime from .claude-plugin/plugin.json).",
		`plugin_version=$(sed -n 's/^[[:space:]]*"version"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' "$PLUGIN_ROOT/.claude-plugin/plugin.json") || plugin_version=""`,
		"",
		`# Cadre CLI version for binary downloads. This is pinned at generation time from cadre_cli/_version.py.`,
		`# Regenerating plugin (via 'cadre generate-plugin') updates this to match the repository's CLI version.`,
		fmt.Sprintf(`CADRE_CLI_VERSION="%s"`, cliVersion),
		"",
		"# An explicit binary wins over cache lookup and download. This is the",
		"# supported answer for an air-gapped install, an unsupported platform,",
		"# or a site that mirrors its own builds -- the cases that used to fall",
		"# back to a bundled Python implementation.",
		`if [ -n "${CADRE_BINARY:-}" ]; then`,
		`  [ -x "$CADRE_BINARY" ] || { echo "cadre: CADRE_BINARY is set but not executable: $CADRE_BINARY" >&2; exit 1; }`,
		`  BINARY_CACHE="$CADRE_BINARY"`,
		"else",
		"  # Resolve the binary (locate in cache or download it). A condition, so a",
		"  # failure does not terminate under set -eu before the diagnostic below.",
		`  if [ -z "$CADRE_CLI_VERSION" ] || ! try_resolve_binary; then`,
		`    echo "cadre: could not obtain the cadre binary for this platform." >&2`,
		`    echo "" >&2`,
		`    echo "  platform:  $(uname -s)/$(uname -m)" >&2`,
		`    echo "  version:   ${CADRE_CLI_VERSION:-unset}" >&2`,
		// ${...:-} because set -u is on and try_resolve_binary leaves this
		// unset when it fails before assigning -- the diagnostic must not
		// itself die on the failure path it exists to explain.
		`    echo "  cache:     ${BINARY_CACHE:-<not resolved>}" >&2`,
		`    echo "" >&2`,
		`    echo "The plugin used to fall back to a bundled Python implementation here." >&2`,
		`    echo "It no longer ships one: two implementations of a byte-exact dispatch" >&2`,
		`    echo "contract is the divergence this migration exists to remove." >&2`,
		`    echo "" >&2`,
		`    echo "Fix one of:" >&2`,
		`    echo "  * set CADRE_BINARY to a cadre binary you already have" >&2`,
		`    echo "  * network access to github.com/deagy/cadre releases on first run" >&2`,
		`    echo "  * an unsupported platform -- released binaries cover linux/amd64," >&2`,
		`    echo "    linux/arm64, darwin/amd64, darwin/arm64 and windows/amd64" >&2`,
		`    echo "  * a prepopulated cache: place the binary at the path above" >&2`,
		`    exit 1`,
		"  fi",
		"fi",
		"",
	)
	body = append(body, g.sdlcShellDispatch()...)
	body = append(body,
		"",
		"# Everything else is the binary's own dispatch, including its help and",
		"# unknown-subcommand handling -- one implementation, not two.",
		"#",
		"# $command_name is passed back explicitly: it was shifted off above so",
		"# the sdlc branch could test it, and $@ holds only the arguments after",
		"# it. Exec'ing just $@ silently drops the subcommand, turning",
		"# `cadre select --task x` into `cadre --task x`.",
		`CADRE_REPO_ROOT="$SUITE_ROOT" exec "$BINARY_CACHE" "$command_name" "$@"`,
		"",
	)

	target := filepath.Join(pluginRoot, "bin", "cadre")
	if err := writeFile(target, strings.Join(body, "\n")); err != nil {
		return "", err
	}
	if err := os.Chmod(target, 0o755); err != nil { //nolint:gosec // intentionally executable
		return "", err
	}
	return target, nil
}

// ---------------------------------------------------------------------------
// Suite copy.
// ---------------------------------------------------------------------------

var skillLinkPatterns = []*regexp.Regexp{
	regexp.MustCompile(`\.\./\.agents/skills/([^/]+)`),
	regexp.MustCompile(`\.\./\.claude/skills/([^/]+)`),
}

// isKernelDoc reports whether a docs/ path documents the lifecycle kernel
// rather than the role suite. Those documents describe G1-G10 gate semantics
// and the LangGraph engine -- neither of which the packaged role suite
// contains -- and their relative links point at kernel/ and engine/ siblings
// the package does not ship, so copying them in produces a plugin full of
// dangling links.
func isKernelDoc(relative string) bool {
	for _, part := range strings.Split(relative, "/") {
		if part == "kernel" {
			return true
		}
	}
	return false
}

var suiteRosterRootAllowlist = map[string]bool{
	"roster/catalog.yaml":        true,
	"roster/catalog.schema.json": true,
	// A CLOSED allowlist rather than a directory walk, so an unlisted
	// roster-root file is silently skipped -- and a packaged suite whose
	// roster.json is missing is not a valid roster package, failing in the
	// installed plugin and nowhere in CI.
	"roster/roster.json":                     true,
	"roster/catalog-order.txt":               true,
	"roster/context-pack-order.txt":          true,
	"roster/_catalog_header.yaml.tmpl":       true,
	"roster/runner-capabilities.json":        true,
	"roster/runner-capabilities.schema.json": true,
	"roster/authority/aides.yaml":            true,
	"roster/authority/_template.md.tmpl":     true,
	"roster/README.md":                       true,
	"roster/RUNBOOK.md":                      true,
}

var knowledgeStoreExtras = map[string]bool{
	"roster/knowledge-store/README.md":   true,
	"roster/knowledge-store/SECURITY.md": true,
	// staged_records.py's findings cite this schema by path as the contract a
	// malformed record violated. Packaging the module without it would ship
	// error messages pointing at a file the reader cannot open.
	"roster/knowledge-store/proposed-knowledge.schema.json": true,
}

var contextStoreExtras = map[string]bool{
	"roster/context-store/README.md":   true,
	"roster/context-store/SECURITY.md": true,
}

func (g *pluginGenerator) generateSuiteCopy(pluginRoot string, writeReadme bool) ([]string, error) {
	trackedList, err := gitTrackedFiles(g.repoRoot, "roster")
	if err != nil {
		return nil, err
	}
	tracked := map[string]bool{}
	for _, relative := range trackedList {
		// The packaged suite carries no Python. The wrapper used to exec
		// roster/**/*.py whenever it could not resolve the Go binary, and
		// that fallback is what made these ~24,500 lines part of the
		// distribution. It is gone -- the wrapper now fails with a
		// diagnostic instead -- so the scripts it pointed at are dead weight
		// a consumer would still have to trust and audit.
		//
		// Data is unaffected: role definitions, catalog.yaml, routing.json
		// and the context packs are what the binary actually reads.
		if strings.HasSuffix(relative, ".py") {
			continue
		}
		tracked[relative] = true
	}
	for _, helper := range []string{} {
		if info, err := os.Stat(filepath.Join(g.repoRoot, filepath.FromSlash(helper))); err == nil && !info.IsDir() {
			tracked[helper] = true
		}
	}

	// `catalog` was parsed straight off the worktree copy of catalog.yaml, but
	// `tracked` only reflects git's index -- an uncommitted new role's AGENT.md
	// would otherwise pass silently, then still get a wrapper and an
	// agent-catalog.json entry, producing a package that references a suite
	// file that was never copied. Fail loudly here instead.
	var untrackedRolePaths []string
	for _, agentID := range g.catalogIDs {
		relative := "roster/" + g.meta(agentID)["definition"]
		if !tracked[relative] {
			untrackedRolePaths = append(untrackedRolePaths, relative)
		}
	}
	if len(untrackedRolePaths) > 0 {
		sort.Strings(untrackedRolePaths)
		return nil, fmt.Errorf(
			"roster/catalog.yaml references role definition file(s) not tracked in git; "+
				"commit them (git add) before regenerating the plugin: %s",
			strings.Join(untrackedRolePaths, ", "))
	}

	// The guard that used to sit here required every script named in
	// bin/subcommands.tsv to be tracked and copied into suite/, because the
	// wrapper emitted a case arm exec'ing each one -- an untracked script
	// produced a wrapper pointing at a file the package did not contain.
	//
	// Both halves of that are gone: the table has no script column, and the
	// wrapper execs the Go binary rather than per-subcommand scripts. There
	// is nothing left for it to check.

	rolePaths := map[string]bool{}
	for _, agentID := range g.catalogIDs {
		rolePaths["roster/"+g.meta(agentID)["definition"]] = true
	}

	documentationPaths := map[string]bool{
		"AGENTS.md":       true,
		"CONTRIBUTING.md": true,
		"IDENTITY.md":     true,
	}
	docsRoot := filepath.Join(g.repoRoot, "docs")
	if err := filepath.WalkDir(docsRoot, func(p string, d fs.DirEntry, err error) error {
		if err != nil {
			if os.IsNotExist(err) {
				return nil
			}
			return err
		}
		if d.IsDir() {
			return nil
		}
		rel, relErr := filepath.Rel(g.repoRoot, p)
		if relErr != nil {
			return relErr
		}
		rel = filepath.ToSlash(rel)
		if !isKernelDoc(rel) {
			documentationPaths[rel] = true
		}
		return nil
	}); err != nil && !os.IsNotExist(err) {
		return nil, err
	}

	trackedSorted := make([]string, 0, len(tracked))
	for relative := range tracked {
		trackedSorted = append(trackedSorted, relative)
	}
	sort.Strings(trackedSorted)

	var selected []string
	selectedSet := map[string]bool{}
	add := func(relative string) {
		selected = append(selected, relative)
		selectedSet[relative] = true
	}
	for _, relative := range trackedSorted {
		switch {
		case documentationPaths[relative]:
			add(relative)
		case rolePaths[relative] || suiteRosterRootAllowlist[relative]:
			add(relative)
		case strings.HasPrefix(relative, "roster/context-packs/"):
			add(relative)
		case strings.HasPrefix(relative, "roster/shared/"), strings.HasPrefix(relative, "roster/workflows/"):
			add(relative)
		case strings.HasPrefix(relative, "roster/orchestration/") &&
			!strings.Contains(relative, "/runs/") &&
			!strings.Contains(relative, "/test/") &&
			!strings.Contains(relative, "/examples/") &&
			!strings.HasSuffix(relative, "generate_global_plugin.py") &&
			!strings.HasSuffix(relative, "migrate_execution_summary.py") &&
			!strings.HasSuffix(relative, "plugin_version.py") &&
			// These two scripts import generate_global_plugin.py (excluded
			// above) and their subcommands are already excluded from the
			// packaged bin/cadre wrapper -- packaging them anyway would ship a
			// non-functional entry point that looks runnable but isn't.
			!strings.HasSuffix(relative, "generate_role_metadata.py") &&
			!strings.HasSuffix(relative, "generate_authority_aides.py"):
			add(relative)
		case strings.HasPrefix(relative, "roster/knowledge-store/src/") || knowledgeStoreExtras[relative]:
			add(relative)
		case contextStoreExtras[relative]:
			// The context store's documentation travels with the distribution;
			// its implementation no longer does. roster/context-store/src/ was
			// deleted once `cadre context` was served entirely by the Go
			// binary -- and the packaged bin/cadre execs that binary for every
			// subcommand, with no Python path at all, so the modules were
			// dead weight rather than the "CLI cannot import its own code"
			// hazard this branch was written to avoid.
			add(relative)
		}
	}

	docsSorted := make([]string, 0, len(documentationPaths))
	for relative := range documentationPaths {
		docsSorted = append(docsSorted, relative)
	}
	sort.Strings(docsSorted)
	for _, relative := range docsSorted {
		if selectedSet[relative] {
			continue
		}
		if info, err := os.Stat(filepath.Join(g.repoRoot, filepath.FromSlash(relative))); err != nil || info.IsDir() {
			continue
		}
		add(relative)
	}

	var written []string
	// The packaged README is register-owned (packaging/plugin-README.md) and
	// rendered to two places: the package root, where it is the repository's
	// front page, and suite/README.md, where the packaged docs cross-reference
	// it. The package-root copy is skipped when writeReadme is false: a target
	// that already has its own .codex-plugin/plugin.json is itself a
	// hand-authored downstream package, not a fresh distribution target, and
	// keeps its own README.md untouched.
	readmeRaw, err := os.ReadFile(g.packagingReadme)
	if err != nil {
		return nil, fmt.Errorf("cannot read %s: %w", g.packagingReadme, err)
	}
	packageReadme := string(readmeRaw)
	if writeReadme {
		target := filepath.Join(pluginRoot, "README.md")
		if err := writeFile(target, packageReadme); err != nil {
			return nil, err
		}
		written = append(written, target)
	}
	suiteReadme := filepath.Join(pluginRoot, "suite", "README.md")
	if err := writeFile(suiteReadme, generatedMarker+"\n\n"+packageReadme); err != nil {
		return nil, err
	}
	written = append(written, suiteReadme)

	for _, relative := range selected {
		source := filepath.Join(g.repoRoot, filepath.FromSlash(relative))
		target := filepath.Join(pluginRoot, "suite", filepath.FromSlash(relative))
		if strings.ToLower(filepath.Ext(target)) != ".md" {
			if err := copyFile(source, target); err != nil {
				return nil, err
			}
			written = append(written, target)
			continue
		}
		raw, err := os.ReadFile(source)
		if err != nil {
			return nil, err
		}
		content, err := rewritePackagedMarkdown(string(raw), relative, pluginRoot, filepath.Dir(target))
		if err != nil {
			return nil, fmt.Errorf("%s: %w", relative, err)
		}
		if err := writeFile(target, content); err != nil {
			return nil, err
		}
		written = append(written, target)
	}
	return written, nil
}

// rewritePackagedMarkdown applies every link rewrite the packaged copy of a
// Markdown source needs, then stamps the generated-file marker. Order matters
// and mirrors the Python exactly.
func rewritePackagedMarkdown(content, relative, pluginRoot, targetParent string) (string, error) {
	content = strings.ReplaceAll(content, "../bin/cadre", "../../bin/cadre")

	// Links to the register's top-level README point at the packaged README
	// under suite/. Depth-aware: a plain "../README.md" -> "README.md"
	// substring replace also matches inside "../../README.md" (written by files
	// one level deeper), silently retargeting them to suite/roster/README.md --
	// a file that exists, so no link checker catches it.
	sourceDepth := len(strings.Split(relative, "/")) - 1
	if sourceDepth > 0 {
		rootReadme := strings.Repeat("../", sourceDepth) + "README.md"
		suiteReadme, err := relSlash(targetParent, filepath.Join(pluginRoot, "suite", "README.md"))
		if err != nil {
			return "", err
		}
		content = strings.ReplaceAll(content, rootReadme, suiteReadme)
	}

	// The register's source for the packaged README has no counterpart inside
	// the package; point at the packaged copy of it instead.
	content = strings.ReplaceAll(content, "../packaging/plugin-README.md", "../README.md")

	// Skills are packaged at the package root (skills/<name>/) by default, not
	// under suite/, so a source link into .agents/skills/ would dangle.
	// Computed per file rather than hardcoded, and skill-name-aware because
	// skillPackageTargets retargets some skills into a sub-plugin directory.
	toPackageRoot, err := relSlash(targetParent, pluginRoot)
	if err != nil {
		return "", err
	}
	for _, pattern := range skillLinkPatterns {
		content = pattern.ReplaceAllStringFunc(content, func(match string) string {
			groups := pattern.FindStringSubmatch(match)
			skillName := groups[1]
			packageSubdir := "skills"
			if override, ok := skillPackageTargets[skillName]; ok {
				packageSubdir = override
			}
			return toPackageRoot + "/" + packageSubdir + "/" + skillName
		})
	}

	// Not packaged at all (the package ships no changelog, and tests are
	// excluded), so point at the register instead of dangling.
	content = strings.ReplaceAll(content, "](../CHANGELOG.md)", "]("+registerURL+"/blob/main/CHANGELOG.md)")
	content = strings.ReplaceAll(content, "](../roster/orchestration/test/",
		"]("+registerURL+"/blob/main/roster/orchestration/test/")

	// A migrated role's AGENT.md starts with `---`-delimited frontmatter;
	// inserting the marker at byte 0 would land it inside that block instead of
	// before it, corrupting it. Insert after the closing delimiter instead.
	if IsMigrated(content) {
		end, ok, err := FrontmatterClosingDelimiterEnd(content)
		if err != nil {
			return "", err
		}
		if ok {
			return content[:end] + "\n\n" + generatedMarker + content[end:], nil
		}
	}
	return generatedMarker + "\n\n" + content, nil
}

// ---------------------------------------------------------------------------
// Package assembly, comparison, and entry point.
// ---------------------------------------------------------------------------

func (g *pluginGenerator) generatePackage(pluginRoot string, writeReadme bool) ([]string, error) {
	if err := resetGeneratedContent(pluginRoot, writeReadme); err != nil {
		return nil, err
	}
	var written []string
	skills, err := g.generateSkillCopies(pluginRoot)
	if err != nil {
		return nil, err
	}
	written = append(written, skills...)

	suite, err := g.generateSuiteCopy(pluginRoot, writeReadme)
	if err != nil {
		return nil, err
	}
	written = append(written, suite...)

	agents, err := g.generateAgentWrappers(pluginRoot)
	if err != nil {
		return nil, err
	}
	written = append(written, agents...)

	provider, err := g.generateProviderCopy(pluginRoot)
	if err != nil {
		return nil, err
	}
	written = append(written, provider...)

	kernel, err := g.generateKernelCompatibility(pluginRoot)
	if err != nil {
		return nil, err
	}
	written = append(written, kernel...)

	hook, err := g.generateMainPluginHook(pluginRoot)
	if err != nil {
		return nil, err
	}
	written = append(written, hook...)

	launcher, err := g.generateBinWrapper(pluginRoot)
	if err != nil {
		return nil, err
	}
	written = append(written, launcher)
	return written, nil
}

// generatedFileSet enumerates the files under root that this generator owns.
func generatedFileSet(root string, compareReadme bool) (map[string]bool, error) {
	out := map[string]bool{}
	err := filepath.WalkDir(root, func(p string, d fs.DirEntry, err error) error {
		if err != nil {
			if os.IsNotExist(err) {
				return nil
			}
			return err
		}
		if d.IsDir() {
			return nil
		}
		rel, relErr := filepath.Rel(root, p)
		if relErr != nil {
			return relErr
		}
		rel = filepath.ToSlash(rel)
		parts := strings.Split(rel, "/")
		owned := generatedTopLevel[parts[0]]
		if !owned {
			for _, nested := range generatedNestedPaths {
				if rel == nested || strings.HasPrefix(rel, nested+"/") {
					owned = true
					break
				}
			}
		}
		if !owned {
			return nil
		}
		for _, part := range parts {
			if part == "__pycache__" {
				return nil
			}
		}
		if ext := path.Ext(rel); ext == ".pyc" || ext == ".pyo" {
			return nil
		}
		if !compareReadme && rel == "README.md" {
			return nil
		}
		out[rel] = true
		return nil
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

func filesEqual(left, right string, compareReadme bool) (bool, []string, error) {
	leftFiles, err := generatedFileSet(left, compareReadme)
	if err != nil {
		return false, nil, err
	}
	rightFiles, err := generatedFileSet(right, compareReadme)
	if err != nil {
		return false, nil, err
	}
	var differences []string
	for rel := range leftFiles {
		if !rightFiles[rel] {
			differences = append(differences, "missing from target: "+rel)
		}
	}
	for rel := range rightFiles {
		if !leftFiles[rel] {
			differences = append(differences, "unexpected in target: "+rel)
		}
	}
	if len(differences) > 0 {
		sort.Strings(differences)
		return false, differences, nil
	}
	for rel := range leftFiles {
		leftBytes, err := os.ReadFile(filepath.Join(left, filepath.FromSlash(rel)))
		if err != nil {
			return false, nil, err
		}
		rightBytes, err := os.ReadFile(filepath.Join(right, filepath.FromSlash(rel)))
		if err != nil {
			return false, nil, err
		}
		if string(leftBytes) != string(rightBytes) {
			differences = append(differences, "content differs: "+rel)
		}
	}
	sort.Strings(differences)
	return len(differences) == 0, differences, nil
}

// PluginResult reports one generate-plugin run.
type PluginResult struct {
	OutputRoot  string
	Written     []string
	WroteReadme bool
	// Differences is populated in check mode and empty when the package is
	// current.
	Differences []string
	Current     bool
}

// GeneratePluginOptions carries the flags `cadre generate-plugin` accepts.
type GeneratePluginOptions struct {
	Check bool
	// ForceReadme writes the register's own README.md over an existing
	// downstream package's README.md.
	ForceReadme bool
}

// RunGeneratePlugin is the `cadre generate-plugin` implementation. It mirrors
// generate_global_plugin.py's main().
func RunGeneratePlugin(repoRoot, outputRoot string, options GeneratePluginOptions) (*PluginResult, error) {
	absOutput, err := filepath.Abs(filepath.FromSlash(outputRoot))
	if err != nil {
		return nil, fmt.Errorf("cannot resolve output root: %w", err)
	}

	// An existing .codex-plugin/plugin.json at the target means it is already
	// an initialized, hand-authored downstream package -- not a fresh
	// distribution target -- so its own README.md is downstream-owned and must
	// survive regeneration untouched.
	markerInfo, markerErr := os.Stat(filepath.Join(absOutput, ".codex-plugin", "plugin.json"))
	preexistingMarker := markerErr == nil && !markerInfo.IsDir()
	writeReadme := options.ForceReadme || !preexistingMarker

	if !options.Check {
		if entries, err := os.ReadDir(absOutput); err == nil {
			if len(entries) > 0 && !preexistingMarker {
				return nil, errors.New("--output must be a new directory or an existing generated plugin")
			}
		} else if !os.IsNotExist(err) {
			return nil, fmt.Errorf("cannot read output directory: %w", err)
		}
	}

	generator, err := newPluginGenerator(repoRoot)
	if err != nil {
		return nil, err
	}

	if options.Check {
		temporary, err := os.MkdirTemp("", "cadre-plugin-")
		if err != nil {
			return nil, err
		}
		defer os.RemoveAll(temporary) //nolint:errcheck // best-effort cleanup
		candidate := filepath.Join(temporary, "cadre")
		if _, err := generator.generatePackage(candidate, true); err != nil {
			return nil, err
		}
		if _, err := os.Stat(absOutput); err != nil {
			return &PluginResult{
				OutputRoot:  absOutput,
				Current:     false,
				Differences: []string{"output directory does not exist: " + absOutput},
			}, nil
		}
		current, differences, err := filesEqual(candidate, absOutput, writeReadme)
		if err != nil {
			return nil, err
		}
		result := &PluginResult{OutputRoot: absOutput, Current: current, Differences: differences}
		if !current {
			return result, nil
		}
		if err := validateProviderBundle(repoRoot); err != nil {
			return nil, err
		}
		return result, nil
	}

	written, err := generator.generatePackage(absOutput, writeReadme)
	if err != nil {
		return nil, err
	}
	return &PluginResult{
		OutputRoot:  absOutput,
		Written:     written,
		WroteReadme: writeReadme,
		Current:     true,
	}, nil
}

// validateProviderBundle asks the lifecycle kernel to validate the provider
// bundle, when one is resolvable. Silently skipped otherwise -- the kernel is
// an optional, separately versioned dependency.
func validateProviderBundle(repoRoot string) error {
	kernel := os.Getenv("AGENTIC_SDLC_BIN")
	if kernel == "" {
		resolved, err := exec.LookPath("agentic-sdlc")
		if err != nil {
			return nil
		}
		kernel = resolved
	}
	command := exec.Command(kernel, "--provider",
		filepath.Join(repoRoot, "provider", "provider.json"), "provider", "list")
	command.Dir = repoRoot
	output, err := command.CombinedOutput()
	if err != nil {
		return fmt.Errorf("provider validation failed: %s", strings.TrimSpace(string(output)))
	}
	return nil
}

// ---------------------------------------------------------------------------
// Filesystem and git helpers.
// ---------------------------------------------------------------------------

func writeFile(path, content string) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("cannot create directory %s: %w", filepath.Dir(path), err)
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return fmt.Errorf("cannot write %s: %w", path, err)
	}
	return nil
}

// copyFile mirrors shutil.copy2: contents plus the source's permission bits.
func copyFile(source, target string) error {
	info, err := os.Stat(source)
	if err != nil {
		return err
	}
	content, err := os.ReadFile(source)
	if err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
		return err
	}
	if err := os.WriteFile(target, content, info.Mode().Perm()); err != nil {
		return err
	}
	return os.Chmod(target, info.Mode().Perm())
}

// copyTree copies a directory verbatim, refusing symlinks rather than
// dereferencing them (which would silently vendor out-of-tree content into a
// published package).
func copyTree(source, target string) ([]string, error) {
	var copied []string
	err := filepath.WalkDir(source, func(p string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		rel, relErr := filepath.Rel(source, p)
		if relErr != nil {
			return relErr
		}
		destination := filepath.Join(target, rel)
		info, lstatErr := os.Lstat(p)
		if lstatErr != nil {
			return lstatErr
		}
		if info.Mode()&os.ModeSymlink != 0 {
			return fmt.Errorf("%s: symlinks are not packaged; replace it with a regular file", p)
		}
		if d.IsDir() {
			return os.MkdirAll(destination, 0o755)
		}
		if err := copyFile(p, destination); err != nil {
			return err
		}
		copied = append(copied, destination)
		return nil
	})
	if err != nil {
		return nil, err
	}
	sort.Strings(copied)
	return copied, nil
}

func listFiles(root string) ([]string, error) {
	var out []string
	err := filepath.WalkDir(root, func(p string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if !d.IsDir() {
			out = append(out, p)
		}
		return nil
	})
	if err != nil {
		return nil, err
	}
	sort.Strings(out)
	return out, nil
}

// relSlash returns the slash-separated relative path from base to target.
func relSlash(base, target string) (string, error) {
	rel, err := filepath.Rel(base, target)
	if err != nil {
		return "", err
	}
	return filepath.ToSlash(rel), nil
}

// gitTrackedFiles returns the repository-relative paths git tracks under
// pathspec, filtered to those that currently exist as regular files -- the
// same `git ls-files` + is_file() pair the Python generator uses.
func gitTrackedFiles(repoRoot, pathspec string) ([]string, error) {
	command := exec.Command("git", "ls-files", pathspec)
	command.Dir = repoRoot
	output, err := command.Output()
	if err != nil {
		return nil, fmt.Errorf("git ls-files %s failed: %w", pathspec, err)
	}
	var out []string
	for _, line := range pySplitLines(string(output)) {
		if line == "" {
			continue
		}
		if info, err := os.Stat(filepath.Join(repoRoot, filepath.FromSlash(line))); err != nil || info.IsDir() {
			continue
		}
		out = append(out, line)
	}
	sort.Strings(out)
	return out, nil
}

// sdlcShellDispatch is the packaged wrapper's `sdlc` branch.
//
// It stays a special case because `cadre sdlc` shells out to a *separately
// installed* kernel binary and must pass the plugin's own provider.json --
// a path only the wrapper knows, since the binary is resolved from a cache
// directory elsewhere.
//
// AGENTIC_SDLC_BIN is the settings resolver's highest-precedence source, so
// honoring it directly here cannot get the precedence order wrong. Anything
// below it goes through `cadre config resolve`, which is the same chain
// settings.py implemented -- the wrapper no longer needs Python for this.
func (g *pluginGenerator) sdlcShellDispatch() []string {
	return []string{
		`if [ "$command_name" = "sdlc" ]; then`,
		`  sdlc_bin="${AGENTIC_SDLC_BIN:-}"`,
		`  if [ -z "$sdlc_bin" ]; then`,
		`    sdlc_bin=$(CADRE_REPO_ROOT="$SUITE_ROOT" "$BINARY_CACHE" config resolve agentic_sdlc.bin_path) || exit 1`,
		"  fi",
		fmt.Sprintf(`  [ -n "$sdlc_bin" ] || { echo "cadre: install Agentic SDLC %s from https://github.com/deagy/cadre" >&2; exit 1; }`,
			g.kernelRequirementText()),
		`  exec "$sdlc_bin" --provider "$PLUGIN_ROOT/provider.json" "$@"`,
		"fi",
	}
}
