#!/usr/bin/env python3
"""Guards the release-asset naming contract the packaged plugin's binary
delivery mechanism depends on.

`plugin/bin/cadre` (generated by
`roster/orchestration/src/generate_global_plugin.py`'s `generate_bin_wrapper()`)
is designed to resolve a per-platform compiled `cmd/cadre` binary against a
fixed naming contract agreed with the release workflow:

    cadre-v<version>-<goos>-<goarch>.tar.gz   (all platforms except Windows)
    cadre-v<version>-<goos>-<goarch>.zip      (Windows)

each containing a single executable named `cadre` (`cadre.exe` on Windows).

That contract has three independent sources of truth that must agree, none
of which imports another, so nothing but a test keeps them aligned:

* `plugin/tools/binary_platforms.py` -- the actual platform matrix and
  naming helpers (import this from CI too; do not depend on this test
  module, which is not guaranteed stable for a non-test consumer).
* `Makefile`'s `cross-build` target -- the GOOS/GOARCH matrix actually built.
* `DISTRIBUTION.md` -- the documented artifact list and naming pattern a
  human or release-automation author reads.
* the release workflow (`.github/workflows/release.yml`) that publishes the
  archives -- out of this test's scope to assert against directly (owned by
  a different workstream), but its asset names are exactly the ones derived
  from the other two here.

This test does not (yet) assert anything about `plugin/bin/cadre` resolving
or downloading a binary at runtime -- see DISTRIBUTION.md's "Current status"
section for why that activation is currently blocked, independent of this
naming contract being correct.

    python3 -m unittest discover -s plugin/tools -p "test_*.py"
"""

from __future__ import annotations

import re
import sys
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from binary_platforms import SUPPORTED_PLATFORMS, archive_extension, archive_name, executable_name  # noqa: E402

REPO_ROOT = Path(__file__).resolve().parents[2]
MAKEFILE = REPO_ROOT / "Makefile"
DISTRIBUTION_DOC = REPO_ROOT / "DISTRIBUTION.md"


class TestCrossBuildMatrixMatchesContract(unittest.TestCase):
    def setUp(self) -> None:
        self.makefile_text = MAKEFILE.read_text(encoding="utf-8")
        cross_build_match = re.search(
            r"^cross-build:\n((?:\t.*\n?)+)", self.makefile_text, re.MULTILINE
        )
        self.assertIsNotNone(cross_build_match, "Makefile has no cross-build recipe")
        self.recipe = cross_build_match.group(1)

    def test_every_contracted_platform_is_built(self) -> None:
        for goos, goarch in SUPPORTED_PLATFORMS:
            with self.subTest(platform=f"{goos}-{goarch}"):
                self.assertRegex(
                    self.recipe,
                    rf"GOOS={goos}\s+GOARCH={goarch}\b",
                    f"cross-build does not build {goos}/{goarch}",
                )

    def test_cross_build_does_not_build_an_uncontracted_platform(self) -> None:
        """Catches the inverse drift: a platform added to the Makefile but
        never added to SUPPORTED_PLATFORMS/DISTRIBUTION.md -- including
        windows/arm64, deliberately excluded (see binary_platforms.py's
        module docstring): a hosted windows-latest runner cannot cross-build
        it with CGO_ENABLED=1, so its reappearance in the Makefile would be
        a release-blocking regression, not a welcome addition."""
        built = set(re.findall(r"GOOS=(\S+)\s+GOARCH=(\S+)", self.recipe))
        contracted = set(SUPPORTED_PLATFORMS)
        self.assertEqual(built, contracted, f"built={built} contracted={contracted}")

    def test_cross_build_sets_cgo_enabled_for_every_platform_line(self) -> None:
        """The knowledge store (github.com/mattn/go-sqlite3) requires cgo.
        A cross-build line without CGO_ENABLED=1 silently produces a binary
        whose `cadre knowledge` subcommand is a non-functional stub -- this
        was verified against a real build, not inferred; see this test
        module's docstring and the Makefile comment above cross-build."""
        for line in self.recipe.splitlines():
            if "GOOS=" not in line:
                continue
            with self.subTest(line=line.strip()):
                self.assertIn("CGO_ENABLED=1", line)


class TestDistributionDocMatchesContract(unittest.TestCase):
    def setUp(self) -> None:
        self.doc_text = DISTRIBUTION_DOC.read_text(encoding="utf-8")

    def test_every_contracted_platform_extension_is_documented(self) -> None:
        """DISTRIBUTION.md documents the naming *pattern*
        (`cadre-v<version>-<goos>-<goarch>.<ext>`) rather than one literal
        archive name per platform, so this checks each platform's goos/goarch
        pair AND its correct extension appear together nearby in the text --
        not merely that the goos/goarch pair appears somewhere, which would
        pass even if the doc claimed the wrong extension for that platform.

        Regression check: inserting a windows/arm64 entry documented with
        the wrong extension (`.tar.gz` instead of `.zip`) must fail this
        test, not just be silently absent from the platform loop below.
        """
        for goos, goarch in SUPPORTED_PLATFORMS:
            ext = archive_extension(goos)
            ext_pattern = r"tar\.gz" if ext == "tar.gz" else "zip"
            wrong_ext_pattern = "zip" if ext == "tar.gz" else r"tar\.gz"
            with self.subTest(platform=f"{goos}-{goarch}"):
                # The correct extension must appear within a bounded window
                # of the goos/goarch pair somewhere in the doc...
                self.assertRegex(
                    self.doc_text,
                    rf"{goos}.{{0,40}}{goarch}.{{0,120}}{ext_pattern}"
                    rf"|{ext_pattern}.{{0,120}}{goos}.{{0,40}}{goarch}",
                    f"{goos}/{goarch} is not documented with its correct extension ({ext})",
                )
                # ...and the wrong extension must NOT be the one associated
                # with this platform (catches a windows/* entry mistakenly
                # given .tar.gz, or a non-windows entry mistakenly given
                # .zip, even if the correct extension also happens to appear
                # elsewhere in the doc for an unrelated platform).
                self.assertNotRegex(
                    self.doc_text,
                    rf"{goos}.{{0,40}}{goarch}.{{0,40}}{wrong_ext_pattern}"
                    rf"|{wrong_ext_pattern}.{{0,40}}{goos}.{{0,40}}{goarch}",
                    f"{goos}/{goarch} appears paired with the wrong extension ({wrong_ext_pattern})",
                )

    def test_archive_naming_pattern_is_stated_literally(self) -> None:
        """Pins the exact pattern string so a documentation edit that
        reflows or paraphrases the contract (e.g. drops the leading
        `cadre-v`, or the goos/goarch ordering) fails loudly instead of
        drifting from what the release workflow and the shim actually use.
        """
        self.assertIn("cadre-v<version>-<goos>-<goarch>", self.doc_text)

    def test_doc_does_not_claim_an_uncontracted_platform(self) -> None:
        documented_archives = set(
            re.findall(r"cadre-v[\w.\-]+-([a-z]+)-([a-z0-9]+)\.(?:tar\.gz|zip)", self.doc_text)
        )
        contracted = {(goos, goarch) for goos, goarch in SUPPORTED_PLATFORMS}
        undocumented_extras = documented_archives - contracted
        self.assertFalse(
            undocumented_extras,
            f"DISTRIBUTION.md names platform(s) not in SUPPORTED_PLATFORMS: {undocumented_extras}",
        )


class TestArchiveContentsContractIsInternallyConsistent(unittest.TestCase):
    """Not a filesystem check -- there is no built archive to inspect in this
    test's scope, and this class has no teeth against any real
    implementation: it only asserts binary_platforms.py's helper functions
    agree with binary_platforms.py's own constant, so only an arithmetic
    mistake inside that one module could ever fail it. Kept as scaffolding
    for a resolver that does not exist yet (see DISTRIBUTION.md's blocker),
    not counted as coverage of anything external.
    """

    def test_windows_platforms_use_zip_and_exe_suffix(self) -> None:
        for goos, goarch in SUPPORTED_PLATFORMS:
            if goos != "windows":
                continue
            with self.subTest(platform=f"{goos}-{goarch}"):
                self.assertTrue(archive_name(goos, goarch).endswith(".zip"))
                self.assertEqual(executable_name(goos), "cadre.exe")

    def test_non_windows_platforms_use_tar_gz_and_bare_executable(self) -> None:
        for goos, goarch in SUPPORTED_PLATFORMS:
            if goos == "windows":
                continue
            with self.subTest(platform=f"{goos}-{goarch}"):
                self.assertTrue(archive_name(goos, goarch).endswith(".tar.gz"))
                self.assertEqual(executable_name(goos), "cadre")


if __name__ == "__main__":
    unittest.main()
