// write.go ports settings.py's write_setting: atomic, containment-checked
// writes to the project-local or user-global config file, preserving
// unrecognized existing keys.
package config

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"

	"gopkg.in/yaml.v3"
)

const headerComment = `# Generated by cadre's settings resolver (internal/config).
#
# Resolution precedence per field: environment variable > this file's
# project-local counterpart (.agents/cadre.yaml, only for fields not marked
# global-only) > this user-global file > built-in default > interactive
# prompt.
#
# Secrets (service tokens, API keys) are never read from or written to this
# file -- they are always environment-variable only.
`

// WriteSetting writes value for key into the project-local or user-global
// config file, atomically, preserving unrecognized existing keys. Returns
// the written path.
func WriteSetting(key string, rawValue string, tier string, start string) (string, error) {
	s, err := spec(key)
	if err != nil {
		return "", err
	}
	if tier != "project" && tier != "global" {
		return "", settingsErrorf("tier must be 'project' or 'global', got %q", tier)
	}
	if tier == "project" && s.Scope == ScopeGlobalOnly {
		return "", settingsErrorf("%s is global-only and may not be written to the project-local config file", key)
	}

	validated, err := validate(s, rawValue)
	if err != nil {
		return "", err
	}

	var target string
	var fileMode, dirMode os.FileMode

	if tier == "project" {
		projectRoot, ok := findProjectGitRoot(start)
		if !ok {
			return "", settingsErrorf("no project (.git boundary) found above the current directory to write into")
		}
		existingPath, err := ProjectConfigPath(start)
		if err != nil {
			return "", err
		}
		if existingPath != "" {
			target = existingPath
		} else {
			target = filepath.Join(projectRoot, projectConfigDir, projectConfigBasename+".yaml")
		}
		resolvedRoot, err := filepath.Abs(projectRoot)
		if err != nil {
			return "", err
		}
		if !isSameOrDescendant(target, resolvedRoot) {
			return "", settingsErrorf("refusing to write outside the project root (possible symlink escape): %s", target)
		}
		fileMode, dirMode = 0o600, 0o755
	} else {
		target, err = GlobalConfigPath()
		if err != nil {
			return "", err
		}
		globalDir := globalConfigDir()
		ancestor := resolveExistingAncestor(globalDir)
		if !isSameOrDescendant(target, ancestor) {
			return "", settingsErrorf("refusing to write outside the global config directory: %s", target)
		}
		fileMode, dirMode = 0o600, 0o700
	}

	existing := map[string]any{}
	if isFile(target) {
		loaded, err := loadConfigFile(target)
		if err != nil {
			return "", err
		}
		for k, v := range loaded {
			existing[k] = v
		}
	}

	setNested(existing, key, validated)
	existing["schema_version"] = 1

	var content string
	if strings.EqualFold(filepath.Ext(target), ".json") {
		data, err := json.MarshalIndent(existing, "", "  ")
		if err != nil {
			return "", err
		}
		content = string(data) + "\n"
	} else {
		content = headerComment + "\n" + dumpYAMLWithQuotedStrings(existing)
	}

	if err := os.MkdirAll(filepath.Dir(target), dirMode); err != nil {
		return "", err
	}
	if err := writeAtomic(target, content, fileMode); err != nil {
		return "", err
	}
	ResetCache()
	return target, nil
}

func setNested(data map[string]any, key string, value any) {
	parts := strings.Split(key, ".")
	node := data
	for _, part := range parts[:len(parts)-1] {
		existing, ok := node[part].(map[string]any)
		if !ok {
			existing = map[string]any{}
			node[part] = existing
		}
		node = existing
	}
	node[parts[len(parts)-1]] = value
}

// dumpYAMLWithQuotedStrings renders data as YAML with every string scalar
// explicitly double-quoted, closing the "007"/"~"/"yes" YAML-scalar-hazard
// class of bug on read-back (an unquoted 007 or yes would otherwise
// round-trip as a number or boolean, not the string it was written as).
func dumpYAMLWithQuotedStrings(data map[string]any) string {
	node := &yaml.Node{}
	_ = node.Encode(quoteAllStrings(data))
	forceQuoteStrings(node)
	out, err := yaml.Marshal(node)
	if err != nil {
		// Fall back to plain marshaling rather than losing the write
		// entirely; the quoting is a read-back safety net, not the only
		// thing that makes this valid YAML.
		out, _ = yaml.Marshal(data)
	}
	return string(out)
}

func quoteAllStrings(v any) any {
	switch val := v.(type) {
	case map[string]any:
		out := make(map[string]any, len(val))
		for k, item := range val {
			out[k] = quoteAllStrings(item)
		}
		return out
	case []any:
		out := make([]any, len(val))
		for i, item := range val {
			out[i] = quoteAllStrings(item)
		}
		return out
	default:
		return v
	}
}

// forceQuoteStrings walks an encoded yaml.Node tree and sets DoubleQuoted
// style on every scalar string node.
func forceQuoteStrings(node *yaml.Node) {
	if node.Kind == yaml.ScalarNode && node.Tag == "!!str" {
		node.Style = yaml.DoubleQuotedStyle
	}
	for _, child := range node.Content {
		forceQuoteStrings(child)
	}
}

func writeAtomic(path, content string, mode os.FileMode) error {
	dir := filepath.Dir(path)
	tmp, err := os.CreateTemp(dir, "."+filepath.Base(path)+".*.tmp")
	if err != nil {
		return err
	}
	tmpName := tmp.Name()
	if _, err := tmp.WriteString(content); err != nil {
		tmp.Close()
		os.Remove(tmpName)
		return err
	}
	if err := tmp.Close(); err != nil {
		os.Remove(tmpName)
		return err
	}
	if err := os.Chmod(tmpName, mode); err != nil {
		os.Remove(tmpName)
		return err
	}
	if err := os.Rename(tmpName, path); err != nil {
		os.Remove(tmpName)
		return err
	}
	return nil
}

// stringifyForDisplay renders a Go value the way Python's repr() would for
// settings.py's prompt/error text -- only used for human-facing messages,
// never for a value that round-trips through validation.
func stringifyForDisplay(v any) string {
	switch val := v.(type) {
	case nil:
		return "None"
	case bool:
		if val {
			return "True"
		}
		return "False"
	case string:
		return strconv.Quote(val)
	default:
		return fmt.Sprintf("%v", val)
	}
}
