// Package requirementissues publishes requirement items as GitLab issues.
//
// Ported from engine/agentic_sdlc_langgraph/requirement_issues.py. This is the
// module that takes operator- and model-supplied text and writes it into a
// real GitLab project, so most of it is refusal rather than transformation:
// what cannot be made safe is rejected outright rather than escaped and hoped
// for.
package requirementissues

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"regexp"
	"strings"
	"unicode/utf8"

	"golang.org/x/text/unicode/norm"
)

// FixedLabel is applied to every issue this module creates.
const FixedLabel = "agentic-sdlc"

// Limits on operator-supplied content.
const (
	MaxTitleLength       = 200
	MaxDescriptionLength = 8000
	DefaultMaxItems      = 50
)

// ProvenanceBanner and RefLinePrefix are emitted only by this module. Content
// carrying either is refused, so a rendered body cannot be forged by supplying
// text that looks like this module's own output.
const (
	ProvenanceBanner = "> Generated by Agentic SDLC"
	RefLinePrefix    = "> ref "
)

// zeroWidthSpace defuses an autolink without making text unreadable.
const zeroWidthSpace = "​"

// Error is a refusal the caller must fix.
type Error struct{ Message string }

func (e Error) Error() string { return e.Message }

func errorf(format string, args ...any) error { return Error{Message: fmt.Sprintf(format, args...)} }

// Blocked reports that publishing is not permitted in the run's current state.
type Blocked struct{ Message string }

func (b Blocked) Error() string { return b.Message }

var (
	itemKeyPattern      = regexp.MustCompile(`^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$`)
	labelCharsetPattern = regexp.MustCompile(`^[a-z0-9-]+$`)
	mentionPattern      = regexp.MustCompile(`(^|[^\w])@(\w[\w.-]*)`)
	crossRefPattern     = regexp.MustCompile(`(^|[^\w])([\w.-]+/[\w.-]+)?#(\d+)`)
)

// forbiddenDescriptionRunes are the separators Python's splitlines() treats as
// line breaks but a plain split on "\n" does not.
//
// Rejected at the source rather than handled. Every downstream check here is
// line-oriented -- a line starting with "/" is a GitLab quick action -- and if
// the splitter used for checking disagrees with the one used for rendering, a
// payload can hide on a line the checker never sees. Refusing the characters
// makes the two agree by construction.
var forbiddenDescriptionRunes = map[rune]bool{
	'\v': true, '\f': true, '\x1c': true, '\x1d': true, '\x1e': true,
	'': true, ' ': true, ' ': true,
}

// ComputeMarker is the hashed identity of one item.
//
// Hashed because the raw task id is operator-chosen, may be sensitive, and the
// target GitLab project may be visible far more widely than the repository the
// task came from.
func ComputeMarker(taskID, gateID, itemKey string) string {
	digest := sha256.Sum256([]byte(taskID + "\x00" + gateID + "\x00" + itemKey))
	return hex.EncodeToString(digest[:])[:16]
}

// TaskHash is the task's own hashed identity, for the body's ref line.
func TaskHash(taskID string) string {
	digest := sha256.Sum256([]byte(taskID))
	return hex.EncodeToString(digest[:])[:16]
}

// ItemLabel is the label that anchors an item to its issue.
//
// The label, not the body text, is the trust anchor: body content is
// searchable and forgeable, whereas a label is set by whoever created the
// issue. The charset is re-checked rather than assumed, because a label GitLab
// silently mangles would break idempotency and publish duplicates.
func ItemLabel(marker string) (string, error) {
	label := "agentic-sdlc-item-" + marker
	if !labelCharsetPattern.MatchString(label) {
		return "", errorf("computed label %q violates the [a-z0-9-] label charset", label)
	}
	return label, nil
}

// ValidateItemKey checks an item key's shape.
func ValidateItemKey(key string) error {
	if !itemKeyPattern.MatchString(key) {
		return errorf("item key %q must match [A-Za-z0-9][A-Za-z0-9._-]{0,63}", key)
	}
	return nil
}

// hasLoneSurrogate reports whether text carries an unpaired surrogate.
//
// Go strings hold bytes, so a surrogate arrives as invalid UTF-8 rather than
// as a rune. Either way it must not reach an API expecting well-formed UTF-8,
// where it may be replaced, rejected, or -- worst -- silently altered into
// something that no longer matches what was checked.
func hasLoneSurrogate(text string) bool {
	if !utf8.ValidString(text) {
		return true
	}
	for _, character := range text {
		if character >= 0xD800 && character <= 0xDFFF {
			return true
		}
	}
	return false
}

// SanitizeTitle normalises and constrains a title, or refuses it.
//
// Printable ASCII only, after NFKC normalisation. A title is short, appears in
// listings and notifications, and has no legitimate need for anything else --
// while a homoglyph or a bidirectional control in one is a display-spoofing
// tool. Normalising first means a lookalike cannot pass by decomposing into
// characters that individually look acceptable.
func SanitizeTitle(title, itemKey string) (string, error) {
	normalised := norm.NFKC.String(title)
	for _, character := range normalised {
		if character < 0x20 || character > 0x7E {
			return "", errorf("item %q: title contains a non-printable-ASCII character (U+%04X)",
				itemKey, character)
		}
	}
	stripped := strings.TrimSpace(normalised)
	if stripped == "" {
		return "", errorf("item %q: title is empty after normalization/strip", itemKey)
	}
	// A leading "-" or "/" is how a title becomes an argument or a command
	// somewhere downstream.
	if strings.HasPrefix(stripped, "-") || strings.HasPrefix(stripped, "/") {
		return "", errorf("item %q: title must not start with '-' or '/'", itemKey)
	}
	if len([]rune(stripped)) > MaxTitleLength {
		return "", errorf("item %q: title exceeds %d characters", itemKey, MaxTitleLength)
	}
	return stripped, nil
}

// neutralizeReferences defuses @mentions and issue cross-references.
//
// A zero-width space after the sigil stops autolinking without making the text
// unreadable. Left alone, a description could notify arbitrary users or
// cross-link arbitrary issues in the target project -- from model-generated
// text.
func neutralizeReferences(text string) string {
	text = mentionPattern.ReplaceAllString(text, "${1}@"+zeroWidthSpace+"${2}")
	text = crossRefPattern.ReplaceAllString(text, "${1}${2}#"+zeroWidthSpace+"${3}")
	return text
}

// SanitizeDescription constrains a description, or refuses it.
func SanitizeDescription(description, itemKey string) (string, error) {
	for _, character := range description {
		if forbiddenDescriptionRunes[character] {
			return "", errorf(
				"item %q: description contains a forbidden control/line-separator character (U+%04X)",
				itemKey, character)
		}
	}
	if hasLoneSurrogate(description) {
		return "", errorf("item %q: description contains a lone Unicode surrogate", itemKey)
	}

	for _, line := range strings.Split(description, "\n") {
		// A GitLab quick action: "/assign @someone", "/confidential". These
		// execute rather than render, so an issue body is an instruction
		// channel unless this refuses.
		if strings.HasPrefix(strings.TrimSpace(line), "/") {
			return "", errorf(
				"item %q: description contains a line starting with '/' (GitLab quick-action injection risk)",
				itemKey)
		}
		if strings.HasPrefix(line, RefLinePrefix) || strings.HasPrefix(line, ProvenanceBanner) {
			return "", errorf("item %q: description contains the reserved provenance/ref-line prefix", itemKey)
		}
	}

	sanitized := neutralizeReferences(description)
	// Checked after neutralisation, which only ever grows the string.
	if len([]rune(sanitized)) > MaxDescriptionLength {
		return "", errorf("item %q: description exceeds %d characters", itemKey, MaxDescriptionLength)
	}
	return sanitized, nil
}

// fenceLength picks a code fence longer than any backtick run inside the text.
//
// Without this, a description containing a fence closes ours early and
// everything after it renders as markdown -- which is how sanitised content
// becomes active formatting again.
func fenceLength(text string) int {
	longest, current := 0, 0
	for _, character := range text {
		if character == '`' {
			current++
			if current > longest {
				longest = current
			}
			continue
		}
		current = 0
	}
	if longest+1 > 3 {
		return longest + 1
	}
	return 3
}

// RenderBody builds an issue body around already-sanitised content.
//
// The task id never appears; its hash does. The ref line is a human-readable
// hint only -- the label is the trust anchor, because body text is both
// searchable and forgeable.
func RenderBody(taskID, gateID, marker, sanitizedDescription string) string {
	fence := strings.Repeat("`", fenceLength(sanitizedDescription))
	var body strings.Builder
	body.WriteString(ProvenanceBanner + "\n")
	body.WriteString(RefLinePrefix + "task:" + TaskHash(taskID) + " gate:" + gateID + " item:" + marker + "\n\n")
	body.WriteString(fence + "\n")
	body.WriteString(sanitizedDescription)
	if !strings.HasSuffix(sanitizedDescription, "\n") {
		body.WriteString("\n")
	}
	body.WriteString(fence + "\n")
	return body.String()
}

// CheckPublishEligibility refuses to publish from a run not in a state to
// publish from.
//
// Each case is a run whose gate content cannot be trusted to represent an
// agreed requirement: a halted run was refused authorisation, a gate awaiting
// re-entry has been superseded, and a blocked or invalidated gate is not a
// basis for anything.
func CheckPublishEligibility(runHalted bool, requiredReentryGate, gateStatus string) error {
	if runHalted {
		return Blocked{"task run is halted (mutation-gate rejection) -- cannot publish requirement issues"}
	}
	if requiredReentryGate != "" {
		return Blocked{fmt.Sprintf(
			"gate has a pending required_reentry_gate=%q -- resolve reentry first", requiredReentryGate)}
	}
	if gateStatus == "blocked" || gateStatus == "invalidated" {
		return Blocked{fmt.Sprintf("gate status %q is not publish-eligible", gateStatus)}
	}
	return nil
}
